### ISSUE TITLE
[Feature Request] Scale snapping

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#104]
It would be nice if the snap to grid functionality would also affect the scaling of sprites. That way uniform scaling of different sprites would be easier.

**Comment by 4ian** [comment]
That's true, that would be handy :)

**Comment by Wend1go** [comment]
Commit https://github.com/4ian/GD/commit/a9cace5ac84c1963a81dbbb701ef5ad9fa48a2b5 implemented this feature
