### ISSUE TITLE
Release GD 3.7.80 on Ubuntu 15.04

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#114]
Release GD 3.7.80 on Ubuntu 15.04

**Comment by 4ian** [comment]
Ah yes indeed! Launched the packaging for Ubuntu Vivid Vervet, waiting for Launchpad to build it :)

**Comment by 4ian** [comment]
Published in the PPA. Would need testing, but as Vivid shouldn't differ a lot from the previous versions it should be ok :)
