### ISSUE TITLE
Help links don't work correctly with the new wiki

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#128]
English links work but links for other languages doesn't work anymore as the address changed a bit.

**Comment by 4ian** [comment]
Indeed, they should be manually updated as I added redirections for old English url (en/game_develop/... => gdevelop/) but I think I can't add automatic redirections for French pages as that would conflict with existing pages :/

**Comment by victorlevasseur** [comment]
Instead of using translations for the different links. Why not use a class gd::HelpLauncher that has a method OpenHelpPage(const std::string &helpPage) ? Then, We just have to call gd::HelpLauncher::OpenHelpPage("documentation/builting/spriteobject"); and the class will automatically open the webpage with the full URL (and add "http://wiki.compilgames.net/" or "http://wiki.compilgames.net/en/"...)

**Comment by 4ian** [comment]
That could even be done in HelpProvider::OpenLink

**Comment by victorlevasseur** [comment]
Done in #207
