### ISSUE TITLE
Show a warning message to the user when he wants to export a game in a non-empty directory.

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#135]
Show a warning message to the user when he wants to export a game in a non-empty directory.
http://forum.compilgames.net/viewtopic.php?f=20&t=6608&p=50921#p50921

**Comment by 4ian** [comment]
Fixed in https://github.com/4ian/GD/commit/dede5434b27d3c6de307fbcc4b7838f57f2db8bc
