### ISSUE TITLE
Crashes on close on Windows 7

### ISSUE THREAD

**Issue by riban-bw** [4ian/GD#137]
I am using the zip version (non-installer) of GD on Windows 7 Professional 64-bit. When closing GD, an error occurs, presented in a dialog: "GDevelop Integrated Development Environment has stopped working." GD version 3.6.80.0 Release.
I have seen this symptom when developing with wxWidgets when a process attempts to close a window that wxWidgets has already closed due to wxWidget's built-in destructor mechanism. This _may_ be similar.

**Comment by 4ian** [comment]
Hey riban-bw, you may want to launch GD using GDIDE_dev.exe to see what the console is outputting at the end. Also try to launch it with gdb to get a backtrace of the crash.

What is your graphic card? Similar issue have been due SFML and poorly written graphic card driver - try to update them :)

**Comment by riban-bw** [comment]
It seems to stop working whilst trying to unload GDIDE.dll. gdb output:

```
* Deleting single instance checker...
* Clearing icon cache...
* Deleting the crash detection file...
* Shutdown process finished.
Closing GDIDE.dll...
[Thread 9360.0x2b6c exited with code 0]
[Thread 9360.0x1458 exited with code 0]
[Thread 9360.0x1718 exited with code 0]
[Thread 9360.0x1140 exited with code 0]
[Thread 9360.0x17b0 exited with code 0]
[Thread 9360.0x1f70 exited with code 0]
[Thread 9360.0x310c exited with code 0]
[Thread 9360.0x804 exited with code 0]
[Thread 9360.0x273c exited with code 0]
[Thread 9360.0x498 exited with code 0]
gdb: unknown target exception 0xc000000d at 0x77d658f8

Program received signal ?, Unknown signal.
0x0008d8d8 in ?? ()
```

Graphics card is Intel HD8 Graphics 4400 with driver 10.18.10.3345 (31/10/2013). I can not change the driver on this machine - it is a company machine for which I do not have admin rights.

GD is run as normal (non-admin) user.

**Comment by 4ian** [comment]
Can you try to type `bt` (then press enter) after you get this log?

But for me it's nothing harmful: GD is already entirely closed, it's just the unloading from the memory that trigger the bug, so yeah maybe a video card related issue.

**Comment by riban-bw** [comment]
bt provides:
`
#0  0x0008d8d8 in ?? ()
`

Not harmful but irksome to have to close error window after closing application every time.

**Comment by 4ian** [comment]
I'm afraid I can't do much: I do not have the machine to reproduce the error and this is probably something that is related to a badly implemented driver - there have been lots of issues like this one in the past with SFML. :/ Maybe an update to SFML will change something (should be done in a next release) but honestly I can't do anything else I think.

**Comment by 4ian** [comment]
Closing as this does not seems actionnable.
