### ISSUE TITLE
Internet connection does not work through proxy server

### ISSUE THREAD

**Issue by riban-bw** [4ian/GD#138]
At start-up, GD performs a (optional) check for updates. If this fails, a warning message pops up. This check will fail if connection to the Internet is via a proxy server. It would be advantageous to check for proxy server and / or give user option to configure one. (Some operating systems such as Windows can use a common (IE) setting for proxy server configuration.)

**Comment by 4ian** [comment]
Closing now as don't have any report for this kind of error with GD5
