### ISSUE TITLE
Ubuntu 32-bit not installing from repository

### ISSUE THREAD

**Issue by riban-bw** [4ian/GD#139]
I installed GD on Windows 32-bit and Ubuntu 64-bit but it fails to install on Ubuntu 32-bit (Trusty) from PPA. This seems to be because the 32-bit deb is missing from the PPA.

**Comment by 4ian** [comment]
I do not support GD on Ubuntu 32 bits - I prefer to concentrate on making things work well on 64 bits, as I also have the Windows version and possibly later the Mac OS version to distribute and test.

I know it's a pity but 64 bits is the future and every single computer sold now is 64 bits. :)

**Comment by 4ian** [comment]
Note that if someone has the time to test, maintain and distribute on Ubuntu 32 bits I would be glad to offer a 32 bits version though :)

**Comment by riban-bw** [comment]
Understood! Please add this info to the website. (There is no indication to 32-bit users as to why their attempt to follow the installation instructions fail.) Cheers!

**Comment by lordbitin** [comment]
Any fast solution for Ubuntu 32 bits users?...

**Comment by 4ian** [comment]
You can take a look at compiling GD by yourself, shouldn't be too difficult honestly: http://4ian.github.io/GD-Documentation/GDCore%20Documentation/install_linux_lib.html

Let me know if you have any error, I've put lots of efforts to be sure that the whole process is quite simple and streamlined.

I think some users have reported to be able to compile on Ubuntu 32 bits, if I remember correctly. It may work, it's just that I can't provide "official" support because I never use Ubuntu 32 bits and I really want to encourage adopting Ubuntu 64 bits :)

**Comment by riban-bw** [comment]
I am currently compiling on 32-bit from which I should be able to make a usable version but this isn't ideal for other users (like my son who wants to use this). Launchpad PPA will build the i386 version if configured (in debian/rules I think). Would it be worth enabling this option, even if you state that the 32-bit version is not supported? There are a lot of 32-bit hardware and OS out there so it disadvantages a lot of users and reduces uptake of the product if it is limited to 64-bit only.

**Comment by 4ian** [comment]
Well, I'd like to get in this case a deep feedback about if the software is working well, if preview of native games if working, if compiled native games are working in particular. :) And it would also be interesting to get some statistics about 32 bits vs 64bits usage of Ubuntu, to see if it's even worth spending time on it :)
If this is ok I could consider activating the 32bit build - not sure what is missing exactly for the 32bits as I concentrated only on making the package for 64bits.

**Comment by 4ian** [comment]
I've added a warning on the website. I'm closing the issue but feel free to reopen/make another issue if you still have problems with 32bit Ubuntu.
