### ISSUE TITLE
Unable to build on Ubuntu 15.04 (Vivid) 64-bit

### ISSUE THREAD

**Issue by riban-bw** [4ian/GD#140]
I have followed the instructions to build from source but cmake fails with error:

`
Extracting SFML in ExtLibs/SFML... (can take a bit of time, be patient)
CMake Error at ExtLibs/CMakeLists.txt:10 (ADD_SUBDIRECTORY):
  add_subdirectory given source "SFML" which is not an existing directory.
`

**Comment by victorlevasseur** [comment]
You need to install curl.

**Comment by riban-bw** [comment]
I will try that later, when I get back to my Ubuntu machine.
Please add this dependency to the list at http://4ian.github.io/GD-Documentation/GDCore%20Documentation/install_linux_lib.html.

**Comment by 4ian** [comment]
You can also fork and send a pull request if you know how to use git :)

**Comment by 4ian** [comment]
Updated: http://4ian.github.io/GD-Documentation/GDCore%20Documentation/install_linux_lib.html :smile:

**Comment by riban-bw** [comment]
curl was already installed so does not seem to be the cause of the build failure. The problem was 7za was not installed. The error message did not describe this. Please add p7zip-full to Ubuntu dependency list.

**Comment by 4ian** [comment]
Added. 
But remember you can edit the doc by yourself using GitHub, and they automatically will be submitted to me after: https://github.com/4ian/GD/blob/master/Core/GDCore/DocMainPage.h :smiley:

**Comment by riban-bw** [comment]
This update has not been applied to http://4ian.github.io/GD-Documentation/GDCore%20Documentation/install_linux_lib.html.

**Comment by 4ian** [comment]
Updated, thanks.
