### ISSUE TITLE
Windows 7 crashes on scene editor - scene tab

### ISSUE THREAD

**Issue by lordbitin** [4ian/GD#143]
Hi, 

I cannot start editing or creating a videogame in my Windows 7 laptop. It just crashes when i enter to the scene editor

Thanks in advance
Víctor

**Comment by victorlevasseur** [comment]
Probably not a GDevelop bug as it works on many computers. 
What is your graphic card ? Are the drivers updated ?

**Comment by lordbitin** [comment]
My graphic card is one from the Intel Mobile 4 Series Express Chipset Family...may be too bad :(

I will try updating the drivers.

Thanks for the fast answer!
Víctor

**Comment by victorlevasseur** [comment]
That's definitly what you need to do : the Intel website has an automatic system to show updates.

If it still doesn't work, we can't do anything because the scene editor (and the native games) is based on SFML (a multimedia lib that uses OpenGL internally).

**Comment by lordbitin** [comment]
Solved by updating Graphic Card drivers. Thanks a lot!!!!!

**Comment by victorlevasseur** [comment]
Nice :+1:  ! We should add a topic on the forum about these kinds of bugs.

**Comment by 4ian** [comment]
:+1: I've created a note in the "Bugs reports" forum: http://forum.compilgames.net/viewtopic.php?f=20&t=6705
