### ISSUE TITLE
Tiled sprite always displaying as "invalid image"

### ISSUE THREAD

**Issue by DaVince** [4ian/GD#150]
For some reason, no matter what picture I use, the tiled sprite always seems to think they're an invalid image:
![2015-07-23-130127_1502x926_scrot](https://cloud.githubusercontent.com/assets/105533/8848848/14a9fa9e-313b-11e5-8c8c-ab8ca3b3c0fc.png)

I tested with the following images, but it seems to do this with any:

![grasstile](https://cloud.githubusercontent.com/assets/105533/8848833/f64ef63a-313a-11e5-9617-9e5653dfa084.png) 
![trobbletest](https://cloud.githubusercontent.com/assets/105533/8848993/489ce7ca-313c-11e5-8308-311bc397a7aa.png) 
![testpic](https://cloud.githubusercontent.com/assets/105533/8848998/4eea4c6c-313c-11e5-9c85-4d22a2fcdc2e.png)

Using Ubuntu 15.04 and the PPA release. This is a new, unsaved HTML5 project with files from several different paths.

**Comment by DaVince** [comment]
Terminal output:
```
* Initialization ended.
Sending analytics data...done (201)

(GDIDE:27917): Gtk-CRITICAL **: IA__gtk_window_resize: assertion 'width > 0' failed

(GDIDE:27917): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(GDIDE:27917): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed
ImageManager: Loading . Resource not found.

(GDIDE:27917): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed

(GDIDE:27917): Gtk-CRITICAL **: IA__gtk_window_resize: assertion 'width > 0' failed

(GDIDE:27917): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(GDIDE:27917): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(GDIDE:27917): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(GDIDE:27917): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed
ImageManager: Loading . Resource not found.
```

**Comment by victorlevasseur** [comment]
It seems that you haven't set the image as GDevelop tries to load the ""
image.

**Comment by DaVince** [comment]
Oh, I just realized what is happening. I have clicked and double clicked on pictures in the list, but it seems that is not how you add them - you have to then click on the little + icon next to the "Textures" bit, which I assumed to be a "browse" icon and not of significance.

Thanks for the help. It seems this might be more of a usability (or user? :stuck_out_tongue_closed_eyes:) issue then.

**Comment by 4ian** [comment]
The usability is not optimal here indeed, I guess we should handle the double click to change the image. Looks like the most intuitive behavior.
