### ISSUE TITLE
[Linux] Backspace/cursor behavior odd?

### ISSUE THREAD

**Issue by DaVince** [4ian/GD#151]
I don't know if this is a wxGtk bug or something specific with my system, but reporting anyway.

How to reproduce:

1. Click on any text box. Whether it's in the properties, the search box in the "edit the condition" window, or even in the bug reporter doesn't seem to matter.
1. Type some text.
1. Press backspace.

What happens for me: nothing happens. No text is removed.

1. Press left or right.

What happens for me: again, nothing happens. The cursor's position doesn't change.

Strangely enough, if I press backspace or the arrow keys, minimize GDevelop and then unminimize it, it seems to have performed the backspace/cursor movement actions correctly. For some reason, it is just not doing it properly immediately.

Xubuntu 15.04/Xfce/GDevelop from the official PPA

**Comment by victorlevasseur** [comment]
It's not a bug from GDevelop, it doesn't happen on Windows, nor Fedora 22. Have you tried another windows manager/desktop environment ?

**Comment by victorlevasseur** [comment]
Seems related : https://bugs.launchpad.net/ubuntu/+source/gnucash/+bug/1306500
Try to install dbus-gtk

**Comment by victorlevasseur** [comment]
and dbus-gtk3

**Comment by DaVince** [comment]
You're right, this seems to have been an IBus (the input method editor I use) issue. Once I close IBus it works fine. Installed the libraries (ibus-gtk and ibus-gtk3) but it looks like those will only start working once I restart the system.

**Comment by DaVince** [comment]
(Of special note: GDevelop crashed when I closed IBus... I blame wxWidgets. :P)

**Comment by 4ian** [comment]
Thanks for the follow up! :)
