### ISSUE TITLE
Building with TDM-gcc

### ISSUE THREAD

**Issue by gvanem** [4ian/GD#152]
I'm failing to build using gcc 5.1 and TDM-gcc:
```
[  2%] Built target sfml-system
[  4%] Built target sfml-audio
[ 11%] Built target sfml-window
[ 14%] Built target sfml-network
[ 23%] Built target sfml-graphics
[ 23%] Building CXX object Core/CMakeFiles/GDCore.dir/GDCore/BuiltinExtensions/AdvancedExtension.cpp.obj
In file included from f:/MingW32/TDM-gcc/x86_64-w64-mingw32/include/windows.h:72:0,
                 from f:/MingW32/src/pthreads-w32-2-9-1-release/Pre-built.2/include/pthread.h:198,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/x86_64-w64-mingw32/bits/gthr-default.h:34,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/x86_64-w64-mingw32/bits/gthr.h:148,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/ext/atomicity.h:35,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/bits/basic_string.h:39,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/string:52,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/stdexcept:39,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/array:38,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/tuple:39,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/bits/stl_map.h:63,
                 from f:/MingW32/TDM-gcc/lib/gcc/x86_64-w64-mingw32/5.1.0/include/c++/map:61,
                 from F:/MingW32/src/Games/GameDevelop/src/Core/GDCore/PlatformDefinition/PlatformExtension.h:9,
                 from f:/MingW32/src/Games/GameDevelop/src/Core/GDCore/BuiltinExtensions/AllBuiltinExtensions.h:9,
                 from f:/MingW32/src/Games/GameDevelop/src/Core/GDCore/BuiltinExtensions/AdvancedExtension.cpp:6:
F:/MingW32/src/Games/GameDevelop/src/ExtLibs/wxwidgets/include/wx/msw/winundef.h: In function 'HWND__* CreateDialog(HINSTANCE, LPCTSTR, H
WND, DLGPROC)':
F:/MingW32/src/Games/GameDevelop/src/ExtLibs/wxwidgets/include/wx/msw/winundef.h:38:20: error: cannot convert 'LPCTSTR {aka const char*}'
 to 'LPCWSTR {aka const wchar_t*}' for argument '2' to 'HWND__* CreateDialogParamW(HINSTANCE, LPCWSTR, HWND, DLGPROC, LPARAM)'
             return CreateDialogW(hInstance, pTemplate, hwndParent, pDlgProc);
                    ^
```
etc. etc.

That's after a fresh **git clone** + **cmake -G "MSys Makefiles"** in an empty build-dir.
Seems to be a missing `-DUNICODE` somewhere. What gives?

BTW. I'd rather use MSVC, but cmake says this project needs C++11. Why?

**Comment by victorlevasseur** [comment]
It's cmake -G "MinGW Makefiles".

Le ven. 24 juil. 2015 à 03:46, Gisle Vanem <notifications@github.com> a
écrit :

**Comment by gvanem** [comment]
Victor Levasseur wrote:
> It's cmake -G "MinGW Makefiles".

No, that's even worse. The 'g++' error is unrelated to which cmake generator
I use anyway.

**Comment by 4ian** [comment]
That's a `windows.h` macro polluting the global namespace. Should be easy to fix using some `undef`.
Victor and I are compiling using clang (on OS X) or gcc (4.6+) but never using gcc 5. However, I guess that except for a few errors, it should be easy to fix any warning/error reported by gcc 5.

So for this error, you can try add a `#undef CreateDialog` in the file after all the include. If it's better we'll add it in the file.

**Comment by victorlevasseur** [comment]
@gvanem Did you managed to build GDevelop with GCC 5 ? 
*(you were speaking of MSVC, but it's not possible to build GDevelop with it as the compilator must be bundled with GDevelop so that GDevelop can build the games).*

**Comment by victorlevasseur** [comment]
@gvanem I managed to build GDevelop with GCC 5.1 32 bits (not w64).

**Comment by gvanem** [comment]
@victorlevasseur Which gcc environment was that? The one from http://mingw.org?

**Comment by victorlevasseur** [comment]
No, TDM-GCC (32 bits) 5.1.0 from : http://tdm-gcc.tdragon.net/download (this is a better environment than MinGW)

**Comment by victorlevasseur** [comment]
You should use build the windows-gcc-5.1 branch from my fork (because some files had to be adapted to allow the games compilation to work) : https://github.com/victorlevasseur/GD/tree/windows-gcc-5.1
