### ISSUE TITLE
Compilation error with ReplaceScene()

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#162]
It seems that this function doesn't exist, it's still named ChangeScene in RuntimeSceneTools.h.

**Comment by 4ian** [comment]
Yep there is a typo indeed, I've pushed a fix.
I'm still wondering how I could enhance the scene stack system with a simple way to clear all scene (but the one being played) (to be able to quickly go back to a main menu for example without unpausing all the scenes).
In particular, I'm not sure if I should store the scene stack in the RuntimeGame for native games (like in the HTML5 game engine, where gdjs.RuntimeGame has a _stack member) or not. Putting the scene stack inside RuntimeGame would make sense but also implies making changes in the way CppLayoutPreviewer launch the preview of the scenes.
