### ISSUE TITLE
Tilemap object missing translations

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#163]
The translations for this object were in a separate file which is not bundled anymore with GDevelop. I think we can include them in the main translation file of GDevelop.
By the way, the wxwidgets translations (useful for the default dialog buttons) must be included with GDevelop.

**Comment by Lizard-13** [comment]
I agree, otherwise this extension translation would be very difficult to maintain.

**Comment by 4ian** [comment]
Added the missing translations :)
