### ISSUE TITLE
Update TDM-GCC to 5.1 (Windows)

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#174]
Since GCC 5.0, the C++ standard lib is fully C++11 compliant (with C++14 experimental support) with a new implementation of std::string allowing us to use const_iterators in erase/insert... as defined in the C++11 standard. However, the new C++11 ABI is not used on Fedora (and probably Ubuntu) even if the GCC version is 5.0/5.1/5.2.

http://tdm-gcc.tdragon.net/download

**Comment by victorlevasseur** [comment]
I managed to build GDevelop with GCC 5.1.

**Comment by victorlevasseur** [comment]
Bump on this @4ian.
It would be even better to change from TDM to mingw-w64 because it's more updated and the maintainers are more active than the TDM ones.

**Comment by 4ian** [comment]
How old is the current version of TDM we're using? Is there any potential issue right now or is it just to make sure we are up-to-date?

**Comment by victorlevasseur** [comment]
Almost 2 years. No big problem with it, just wanted to keep it updated (and to be closer to the version used to build GDevelop on Linux : 5.3/6.1).
