### ISSUE TITLE
Parameter's default value is not taken into account if the parameter is not optional

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#176]
Parameter's default value is not taken into account if the parameter is not optional.
See http://forum.compilgames.net/viewtopic.php?p=52691#p52691

**Comment by 4ian** [comment]
With the fix, parameter are now filled in the editor with their default value if they are empty.
The confusion came from the fact that parameters expecting a layer are labelled "Layer (base layer if empty)" . What I meant by "empty" here is an empty string (`""`). Maybe the label should be updated.
