### ISSUE TITLE
Clarify license of IDE.

### ISSUE THREAD

**Issue by Jookia** [4ian/GD#185]
It says it's released under the 'GNU General Public License' in the source headers and 'GPLv3' in the documentation. The source code needs to be updated to reflect this lest it can be taken as GPLv2 or GPLv1. It's also good to note if it's upgradable to the newest version.

**Comment by 4ian** [comment]
Good catch, I guess we should update the source code to indicate the version (v3) :)
Is there any advantages to allow any later version?

**Comment by Jookia** [comment]
Any later version means you can update the entire project to the next version of the GPL when it comes out (if you wish), without getting everyone's permission. Most people don't really want to do this, so the actual advantage is that projects using newer GPL versions can use your code. For instance, I might want to use a cool GPLv4 library as an extension to GDevelop or use some of your code in a GPLv4 project.

**Comment by 4ian** [comment]
I see, thanks for the explanation! Well I guess it may be safer to stay with GPLv3 (because who knows what the the hypothetical v4 could be :)) and it won't be a big deal to quickly review any newer version if needed in the future.
I'm still finishing large changes to the codebase and I'll update the IDE source headers to state that this is GPLv3 :)

**Comment by Jookia** [comment]
Thanks! Just to clarify 'or later' is an option, it doesn't man it automatically get upgraded, it just means newer GPL code is compatible with the license. Otherwise you get in sticky situations where you can't use GPLv2 and GPLv3 code in the same project since the GPLv2 project didn't specify 'or later'. Still, specifying that's it only GPLv3 is just as valid. :) Thanks again!

**Comment by 4ian** [comment]
Mmm I'll still stick with GPLv3 only, as it's stated in the Readme :)
I've pushed changes to clarify the use of the version 3 of the license: https://github.com/4ian/GD/commit/d062d7b6d3742ff01acca3779d329998c049ef77
I'll merge it if it looks good.

**Comment by Jookia** [comment]
Looks very good!

**Comment by 4ian** [comment]
Merged for v4 (that will probably soon be the master, and the old master be v3). Thanks for reporting this issue :+1:
