### ISSUE TITLE
Easy function to replace substring 

### ISSUE THREAD

**Issue by 4ian** [4ian/GD#187]
When working on GDevelop, there is at least 3 different part where I need to replace a substring by anothing in a string:
  * In GDJS/Exporter.cpp (to replace placeholder in generated files)
  * In the code adapting the GDevelop 3.x projects for version 4 (to replace Automatism by Behavior in type names)
  * In EventsRefactor, and potentially in other part of the code base.

It's frustrating to rely on code like:
```
   gd::String search = "toReplace";
    size_t pos = str.find(search);
    if ( pos < str.length() )
        str = str.replace(pos, search.size(), "replacement");
```

just to replace a simple string.
@victorlevasseur do you think we could make a custom replace function? Like a static one:
```
 str = gd::String::replace("toReplace", "replacement");
```

or an overloading of replace member function:

```
 str = str.replace("toReplace", "replacement");
```

Note that this is not a member function following std::string interface, so maybe it should have a capital R to emphasise this (as the other custom methods we added to gd::String).
Finally, we could have a third boolean argument `replaceAll` that defaults to false.

What do you reckon?

**Comment by victorlevasseur** [comment]
Good idea. However, I think we should find another name because it would be easy to misspell it with replace which isn't the same function at all. ```FindAndReplace``` is more appropriate in my opinion (but the name is longer).
```str.FindAndReplace("placeholder", "myStr", true);```

**Comment by 4ian** [comment]
FindAndReplace looks good, because it's exactly what the function does! :)
I'll add it soon (unless you want to implement it)

**Comment by victorlevasseur** [comment]
You can do it if you want ;)

**Comment by 4ian** [comment]
Done in https://github.com/4ian/GD/commit/c369db20ba7275db8ea7e1c179fa9a6150130ae6 ;)
