### ISSUE TITLE
Wrong accented characters in source files

### ISSUE THREAD

**Issue by 4ian** [4ian/GD#190]
@victorlevasseur It seems that the sources are containing bad characters for accented characters (for example https://github.com/4ian/GD/blob/2593a9ef4d68cec81d1f336988fd3daceb37ad86/IDE/Credits.cpp#L223).

I think it was messed up during the refactoring to use gd::String. What should be the rationale for the encoding of the source files? Are we using UTF8?

**Comment by victorlevasseur** [comment]
I think Github assumes that the source files are encoded in UTF8 but this
file is encoded in ISO 8859-1. That's why the accentuated character are
displayed as invalid characters.

Le jeu. 27 août 2015 à 23:16, Florian Rival <notifications@github.com> a
écrit :

**Comment by victorlevasseur** [comment]
There's also a problem here with the degree symbol : https://github.com/4ian/GD/blob/master/Extensions/PhysicsBehavior/Extension.cpp#L218

**Comment by victorlevasseur** [comment]
If you want to keep the file in pure ASCII, we can rewrite these characters using their raw utf8 bits.

**Comment by victorlevasseur** [comment]
By the way, the news message downloaded from the server will need to be encoded in UTF8 for the next version.
