### ISSUE TITLE
Instructions height too small for icons in the event editor

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#192]
The pictures height exceeds the line height by one pixel : 
![instructionheightpb](https://cloud.githubusercontent.com/assets/964512/9629106/75fd28b6-5170-11e5-9b0b-f37dc1907c05.png)
(This is also the case for the "No condition / action" text)

**Comment by 4ian** [comment]
Replace this line: https://github.com/4ian/GD/blob/master/Core/GDCore/IDE/EventsRenderingHelper.cpp#L145

by 
```cpp
    //Update height and ensure it's not too small
    fontCharacterHeight = std::max(dc.GetTextExtent("abcdef").GetHeight(), 15);
```

and tell me if it's better :)

**Comment by victorlevasseur** [comment]
It's better but even better with **16** (so that the bottom part of the icon doesn't hide the instruction list bottom border). I made a small PR with this change : #193

**Comment by 4ian** [comment]
Cool thanks! :)
