### ISSUE TITLE
Problem with collision and hitboxes in HTML5 games

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#198]
It seems there is a problem with custom hitboxes and the collision condition in HTML5 games.
Even if the hitboxes are taken into account, the collision is triggered before the collision between the hitboxes. I think it's related to this condition : https://github.com/4ian/GD/blob/master/GDJS/Runtime/runtimeobject.js#L1024 because the collision condition is the only one that doesn't work correctly (the separateObjects condition works perfectly with the hitboxes).

See http://forum.compilgames.net/viewtopic.php?f=19&t=6968#p53037

**Comment by 4ian** [comment]
Yes good catch, I think that it's an optimisation done at the time when only bounding boxes were supported for collisions. I'm gonna remove it.

**Comment by 4ian** [comment]
Done in https://github.com/4ian/GD/commit/f6a55188c6b133937a25453d0e56db1880efa29c
