### ISSUE TITLE
Certain things slow to load (Music and AdMod banner)

### ISSUE THREAD

**Issue by andresmsgl** [4ian/GD#204]
I have a music file that is reproduce at the beginning of the scene (Play music on a channel), the size of the file is around 1.5 MB.

I export it to Android with cordova, and build it with intel XDK, and when I install the app and run it, take more than 20 seconds to reproduce the music. Same thing happen with the Admob banner, I install third party plugin (cordova plugin Admob basic), setup it, build and install the app in the phone, but the banner NO load at once, it take sometimes more than 30 seconds to show. What can i do?

Thanks.

**Comment by andresmsgl** [comment]
I was checking and it happens in the browser too, the wait is less, but still happens.

**Comment by 4ian** [comment]
For audio, there is indeed some kind of slowdown while loading a music for the first time, in particular on Android (on iOS it's much better - almost no waiting time!). Not sure what I can do about it, maybe try to preload audio files. What you can try is to launch the music at the start of the game, with volume set to 0. That might speed up the loading latter when really launching the music.

For AdMob, it's not related to GDevelop nor the AdMob object: it's just that AdMob might take a while to fetch an ad and send it to the game.

**Comment by andresmsgl** [comment]
Thanks for the answer 4ian, I will try it. Good to know that in OS works better.
