### ISSUE TITLE
Storage actions in HTML5 don't work (through multiple sessions) if the file is not loaded using the "load file" action

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#210]
Storage actions in HTML5 don't work (through multiple sessions, the file is lost at the end of the session) if the file is not loaded using the "load file" action.

**Comment by 4ian** [comment]
Strange, when not using "load file", stored data should be written directly to the browser local storage by each action (instead of being written to the local storage by the unload action). I can't spot any error in the code, do you have an example?

**Comment by victorlevasseur** [comment]
It has been reported on the forum and you can try to reproduce the issue with a simple HTML5 game loading/saving a number.

**Comment by 4ian** [comment]
It's working when saving a number in a preview :confused: I can see the JSON saved in local storage in the Chrome debugger.
Can you give me a link to the thread?

**Comment by victorlevasseur** [comment]
http://forum.compilgames.net/viewtopic.php?f=19&t=7208
Tested on Firefox, the JSON saved file doesn't appear if I don't use the load and close actions.

**Comment by 4ian** [comment]
Fixed, when the virtual "file" wasn't loaded, there were some case for which it wasn't properly persisted in the local storage :)
