### ISSUE TITLE
Can't set up execution engine on game within folders with accentuated letters

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#215]
Seems that the compiled game can't find the Code.dll when the folder contains accentuated letters (on Windows only). Strange, why does GDevelop use the full path to load Code.dll ?

**Comment by 4ian** [comment]
Fixed in https://github.com/4ian/GD/commit/549614adbb265852f83963e90b698e28aca293b7
I've used `GetModuleFileName` instead of `getcwd` which seems to be returning an invalid string on Windows. Also made the loading of library more robust by trying relative filenames as done for the game resources.

**Comment by 4ian** [comment]
@victorlevasseur Could you do a quick check with the latest commit to make sure it's working? :)
