### ISSUE TITLE
Native game compilation freezes when a scene is open on Mate desktop environment

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#217]
When building a native game with no scenes open, it works again.

**Comment by 4ian** [comment]
Had the same problem on OS X: https://github.com/4ian/GD/blob/master/Core/GDCore/IDE/wxTools/SafeYield.h#L31

Maybe we should deactivate this for Linux too? :/

**Comment by victorlevasseur** [comment]
When I deactivate this line, the application still freezes and even freezes
when no scenes are opened :(

Le lun. 30 nov. 2015 à 23:33, Florian Rival <notifications@github.com> a
écrit :

**Comment by victorlevasseur** [comment]
It doesn't happen anymore (at least on Fedora 25 with Mate)
