### ISSUE TITLE
Use std::vector<std::pair<gd::String, gd::PropertyDescriptor>> for gd::Object::GetProperties and GetInstanceProperties

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#223]
The use of std::map forces the properties to be sorted in the alphabetic order (that can vary depending on the language). The use of ```std::vector<std::pair<...>>``` could solve the problem and lets GDevelop and extensions order the properties the way they want (in the insertion order)

**Comment by 4ian** [comment]
On the other side, we're then unable to directly access to properties using `operator[]` and that's really less convenient :/
