### ISSUE TITLE
Firefox already running error when launching HTML5 game

### ISSUE THREAD

**Issue by brylie** [4ian/GD#225]
# Observed behavior
When clicking *Preview*, on Ubuntu 15.10, I get the following error:

```
Firefox is already running, but is not responding. To open a new window, you must first close the existing Firefox process, or restart your system.
```

# Expected behavior
The game preview would open in the existing Firefox process, but in a new tab.

**Comment by victorlevasseur** [comment]
That's what is done on most OS (I'm on Fedora and it opens a new tab). This is not a GDevelop bug.

**Comment by 4ian** [comment]
Not a GDevelop bug in my view too, but more likely a problem of Firefox being unable to open a new tab. The error message of Firefox is quite clear in fact :) ("Firefox is already running, but is not responding")

**Comment by 4ian** [comment]
@brylie Can you double check if the problem is still happening? Maybe you could try to close and relaunch Firefox, or even temporarily switch your default browser to another one to confirm that GDevelop is able to launch it.

**Comment by brylie** [comment]
Yep. The issue is resolved after my computer rebooted. Perhaps there was an upgrade that had not completed, e.g. requiring a Firefox restart.

**Comment by 4ian** [comment]
Ok, thanks for the follow-up :)
