### ISSUE TITLE
Add version number to GDevelop interface

### ISSUE THREAD

**Issue by brylie** [4ian/GD#227]
```
As a bug reporter
I would like to quickly find my GDevelop version
so that I can provide that information with my issue reports
```

# Observed bahavior
It is not easy to determine the GDevelop version number, either from the help menu or the starting screen.

# Expected behavior
The version number would be printed on the help menu, start screen, or some similar location.

**Comment by victorlevasseur** [comment]
The version of GDevelop is shown in the about dialog (Help button on the top right hand corner of the GUI > About ...)

**Comment by 4ian** [comment]
Yep you can see it in the about dialog and for advanced users you can start gdevelop on the command line with `--version` flag to get the version number :)

**Comment by 4ian** [comment]
@brylie Can you find it? If it's ok for you I'll close the issue :smiley:

**Comment by brylie** [comment]
Ah, yep. The help icon is pretty small, but now I see it. Thanks!
