### ISSUE TITLE
Error when starting GDevelop as non priveleged user

### ISSUE THREAD

**Issue by brylie** [4ian/GD#228]
On a fresh installation of GDevelop, I get an error on startup:

```
Error when loading:

... 
May be a missing file or permissions issue.
```

The error is paraphrased, and disappears when launching GDevelop with `sudo` permissions.

**Comment by victorlevasseur** [comment]
Strange. Never saw that error on any linux distro.

Which distro are you using ?

**Comment by 4ian** [comment]
What is the full error message?

**Comment by 4ian** [comment]
@brylie Any update on this problem? Can you launch GDevelop without `sudo`?

**Comment by brylie** [comment]
I have to reinstall. The problem disappeared the first time I launched with sudo permissions. Now I can launch as a standard user.

**Comment by 4ian** [comment]
Closing this as it should be working :)
