### ISSUE TITLE
Not opening on Mac OS X El Capitan

### ISSUE THREAD

**Issue by AnferneeBlijd** [4ian/GD#251]
The Develop.App file does not open. It flashes like it want to open but nothing appears.

**Comment by 4ian** [comment]
Looks like I broke something in the package of the latest version. Thanks for reporting it :)
Can you try this version? https://github.com/4ian/GD/releases/download/4.0.88/GDevelop.pkg

**Comment by victorlevasseur** [comment]
A user has the same problem and has got pretty explicit error message : http://forum.compilgames.net/viewtopic.php?p=55800#p55800

**Comment by 4ian** [comment]
Yup I can reproduce it, it's a bit strange because it's working before packaging but not after.
Anyway I have the exact same error message when launching the packaged version so I should be able to fix it :)

**Comment by mfdeveloper** [comment]
+1 I have the same problem. Using version **4.0.88** on Mac OSX El Capitan, I couldn't importa a image into a Sprite Object. The FileOpen dialog open, but I can't select a image file :(

**Comment by 4ian** [comment]
Closing this, outdated and it's working now :)
