### ISSUE TITLE
Properties panel always off screen

### ISSUE THREAD

**Issue by SolarPolarMan** [4ian/GD#262]
I'm on eOS (Ubuntu 14.04) using two monitors and it always appears off the top left of my second monitor (To the left) and the movement bar is off screen. ALT + F7 can't move it

**Comment by 4ian** [comment]
Can you move the properties panel if you unplug the second monitor and relaunch GD?

**Comment by SolarPolarMan** [comment]
It then is able to be moved. I moved it back on screen then closed gdev. I then plugged my second monitor back in and reopened gdev and it's still on screen :D.

**Comment by SolarPolarMan** [comment]
I guess one solution is to make ALT - F7 work. But it's a work around for now.

**Comment by SolarPolarMan** [comment]
This is still an issue

**Comment by victorlevasseur** [comment]
Can't do much about it. The panels are managed by our GUI library. :(

**Comment by SolarPolarMan** [comment]
:(
