### ISSUE TITLE
Build fails - windows GDevelop from source

### ISSUE THREAD

**Issue by zatsme** [4ian/GD#263]
I have tried a few times to build this and have finally got this far...  Before I had many dev tools on my pc and they were causing other issues!

I have followed the doc and run cmake and then mingw32-make and this is where I get.

any ideas?

```
27%] Linking CXX shared library ..\..\Output\Release_Windows\GDCore.dll
CMakeFiles\GDCore.dir/objects.a(GDCoreDialogs.cpp.obj):GDCoreDialogs.cpp:(.rdata$_ZTV17wxWindowWithItemsI13wxHtmlListBox15wxItemContainerE[__ZTV17wxWindowWithItemsI13wxHtmlListBox15wxItemContainerE]+0x3e4): undefined reference to `non-virtual thunk to wxHtmlListBox::RefreshAll()'
CMakeFiles\GDCore.dir/objects.a(GDCoreDialogs.cpp.obj):GDCoreDialogs.cpp:(.rdata$_ZTV17wxWindowWithItemsI13wxHtmlListBox15wxItemContainerE[__ZTV17wxWindowWithItemsI13wxHtmlListBox15wxItemContainerE]+0x428): undefined reference to `non-virtual thunk to wxHtmlListBox::RefreshRow(unsigned int)'
H:/GDEVEL~1/tdmgcc/bin/../lib/gcc/mingw32/5.1.0/../../../../mingw32/bin/ld.exe: CMakeFiles\GDCore.dir/objects.a(GDCoreDialogs.cpp.obj): bad reloc address 0x428 in section `.rdata$_ZTV17wxWindowWithItemsI13wxHtmlListBox15wxItemContainerE[__ZTV17wxWindowWithItemsI13wxHtmlListBox15wxItemContainerE]'
collect2.exe: error: ld returned 1 exit status
Core\CMakeFiles\GDCore.dir\build.make:4514: recipe for target '../Output/Release_Windows/GDCore.dll' failed
mingw32-make[2]: *** [../Output/Release_Windows/GDCore.dll] Error 1
CMakeFiles\Makefile2:488: recipe for target 'Core/CMakeFiles/GDCore.dir/all' failed
mingw32-make[1]: *** [Core/CMakeFiles/GDCore.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by 4ian** [comment]
This is an error related to wxWidgets.. Do you know if you have a version of wxWidgets installed on your computer? If it's the case, better erase it. CMake should download the appropriate, pre-compiled version for GDevelop when you launch it.

PS: To format your code/console output so that it is perfectly readable, use triple backquotes ``` :wink: I've edited your post

**Comment by zatsme** [comment]
Thanks for fixing the post 😁

I don't have wxwidgets installed anywhere.  Cmake did download both required packages and extracted them.  Any other ideas?

I think my next move is to run a virtual machine and try it,  guaranteed clean PC then 😁

**Comment by 4ian** [comment]
Following the steps from the documentation using a virtual machine is indeed a good idea, as you're sure to have a clean setup. And if something goes wrong, it surely that something is missing in the doc :)

**Comment by zatsme** [comment]
Hopefully can do that tonight after work. 🌃

**Comment by zatsme** [comment]
[mylog.txt](https://github.com/4ian/GD/files/241877/mylog.txt)

Same Problem - VirtualBox - Windows 10 64bit - Cmake 3.5 win32 x86 - tdm gcc 5.1.0-3 - GD-master

Full log attached, help!

**Comment by 4ian** [comment]
Can't see your log, I have a 404 when clicking on the link.

> tdm gcc 5.1.0-3

That's the version that is recommended for building GD :) The version in the documentation (and the version bundled with GD to compile native games) is TDM-GCC 4.9.2 but the link seems broken. Here is the correct one: https://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/Previous/1.1309.0/tdm-gcc-4.9.2.exe/download

But I'm not sot sure it's the source of the error as I can't see the log. 😉

**Comment by zatsme** [comment]
I'm AFK for the day now so can't upload again until later.  I have tried a few different versions of the compiler but used 5.1 as Victor seems to have used it successfully.  Will download and try your version later.  Thanks 😃

**Comment by victorlevasseur** [comment]
If you want to use TDM GCC 5.1, you'll have to build wxwidgets manually (the wxwidgets package downloaded with CMake is compiled for 4.9.2)

**Comment by zatsme** [comment]
Awesome. That must be it 😁

I'll compile with correct version later and then I guess update the docs with version numbers is a good idea 😃

**Comment by zatsme** [comment]
Using 4.9.2 with both my normal and virtual windows 10 completes the compile and generates the executables and DLL's etc... but I get this error during the compile..

```[ 44%] Linking CXX shared library ..\..\Output\Release_Windows\GDCpp.dll
Copying GDC++ and extensions to H:/GdevelopDevelopment/GD-master/Binaries/Output/Release_Windows/CppPlatform...
309 File(s) copied
392 File(s) copied
4578 File(s) copied
0 File(s) copied
84 File(s) copied
7 File(s) copied
Copying GCC compiler to CppPlatform/MinGW32...
MinGW not found!
Done.
[ 44%] Built target GDCpp
Scanning dependencies of target GDCpp_Runtime```

I can run the IDE , preview a game but if I try to export it hangs as mingw32 is not there.  What did I miss?

**Comment by victorlevasseur** [comment]
You need to copy the content of your MinGW folder into GDevelop's
PATH\CppPlatform\MinGW32 .

**Comment by zatsme** [comment]
Did I miss that or is it missing from the doc?

**Comment by victorlevasseur** [comment]
It's probably missing from the doc.

**Comment by zatsme** [comment]
It's all good now :)  I think the docs should state current versions, and where to copy the mingw32 files so you end up with a fully working freshly brewed GDevelop :dancers:

**Comment by 4ian** [comment]
Good to know that it's working now 👍 
The compiler is normally automatically copied but that part failed: `Copying GCC compiler to CppPlatform/MinGW32... MinGW not found!`

What is the path of MinGW for you? We should probably add it to the script doing the copy (https://github.com/4ian/GD/blob/master/GDCpp/scripts/CopyHeadersToGD.bat#L23) There already are a few paths :)

**Comment by zatsme** [comment]
Mine is at the same level directory as gd-master..

Can't you just run ```c++ -print-search-dirs``` and parse the output?

**Comment by 4ian** [comment]
Well I just used the most simple solution :) I guess you could use `c++ -print-search-dirs` but you then have to do more work to parse the output and make sure it works in all cases.
It's feasible, you can try to do it and submit a pull request if you're interested :)
