### ISSUE TITLE
Editor: Scene won't render under a high contrast theme in Windows

### ISSUE THREAD

**Issue by RandomShaper** [4ian/GD#266]
Tested only on my machine: ancient ATI Mobility Radeon HD 4650, Windows 10 x64.

With a normal theme it works perfectly. With a high contrast theme, the area in which the scene should be rendered shows nothing; it keeps showing whatever was formerly visible on that screen area.

**Comment by 4ian** [comment]
Hey @RandomShaper, sorry for answering late I was travelling these last days. Can you upload a quick screenshot of the issue with the high contrast theme? :)

**Comment by RandomShaper** [comment]
For instance, after resizing the window from a small size:
![gd high contrast](https://cloud.githubusercontent.com/assets/11797174/15516451/3dfc58f2-21f3-11e6-919b-2b4b11089eee.png)

**Comment by RandomShaper** [comment]
While contributing to another OSS project afflicted of the same, I found the cause for this and the solution.

As Microsoft explains in [a document about compatibility with high contrast themes](https://msdn.microsoft.com/en-us/library/windows/desktop/hh404233(v=vs.85).aspx#_______supporting_high_contrast_themes_in_windows_8_and_later) for Windows 8 and up the executable manifest must have certain items.

I applied those changes to the manifest of the application I'm contributing to and now it renders perfectly under a high contrast theme, when it did not show anything before the change.

Hope this helps!

**Comment by RandomShaper** [comment]
FYI, [the commit that fixes it for Godot](https://github.com/godotengine/godot/pull/5364/commits/85a5290ee8a4c95be19f086181379330baf0deed).

For a quick test, insert this before the closing `</manifest>` tag in **GDIDE.exe.Manifest**:
```xml
    <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
        <application>
            <!-- Windows 10 -->
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
            <!-- Windows 8.1 -->
            <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
            <!-- Windows 8 -->
            <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
            <!-- Windows 7 -->
            <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
            <!-- Windows Vista -->
            <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
        </application>
    </compatibility>
```

Then switch to a high contrast theme and run **GDIDE.exe** to see it working!

**Comment by 4ian** [comment]
Awesome! If you have some time you can even submit me a PR, otherwise I'll try to do it soon.
Thanks a lot for your research on this problem 😄 👍

**Comment by RandomShaper** [comment]
Here you are! I think that's the way.

**Comment by RandomShaper** [comment]
At Godot we have found issues on some old graphics card with the enhanced manifest.

You can follow our research at [the page for the issue](https://github.com/godotengine/godot/issues/5452).

Anyway, I'll post here what we find.

**Comment by RandomShaper** [comment]
GDevelop, by not requiring h/w acceleration (AFAIK) works for a setup known to give issues in other products (Intel HD 3000 + Windows 10 32-bit). So I think it's safe.

**Comment by 4ian** [comment]
Cool, thanks for the follow-up! 👍

**Comment by victorlevasseur** [comment]
Unfortunately, the new manifest caused some weird behavior in the text object editor (the text size combobox is not rendered correctly).

**Comment by 4ian** [comment]
@RandomShaper Do you have any information about this? Any idea why it would break other controls in the application?

**Comment by RandomShaper** [comment]
AFAIK, GDevelop uses WxWidgets for the UI. May it be an issue with that
library?

Anyway, does it happen only on that specific control?

**Comment by RandomShaper** [comment]
By the way, for me the font size combo box renders well.

Victor, which Windows version are you running?

**Comment by victorlevasseur** [comment]
With or without the Manifest ? Because it doesn't render well on many
computer (mine and many other people on the forum).

**Comment by RandomShaper** [comment]
Perhaps the new manifest must be merged with the one bundled with
wxWidgets. See: https://www.wxwidgets.org/docs/faq/windows/#winxp

**Comment by RandomShaper** [comment]
I've been able to reproduce it after I actally understood the issue. Regarding the manifest provided by wxWidgets, I've seen it's already merged.

Removing the specific tag for Windows 10 from the manifest gets the issue solved while still letting GDevelop work under a high contrast theme. It's expected since the relevant behavior in Windows was introduced in version 8. Probably Windows 10 adds more breaking changes so better to un-target it by now (manifest-wise).

So #271 fixes it.

For a quick test, just remove the tag for Windows 10 from the manifest and restart GDevelop.

**Comment by victorlevasseur** [comment]
In fact, we just revert back to the old manifest.

**Comment by RandomShaper** [comment]
I've checked that when the text object edit dialog is closed, depending on whether the manifiest includes Windows 10 or not, the combo box gets the CB_GETCOMBOBOXINFO message or not (it does when **not** included). So it may be a change in the Windows API or a bug in wxWidgets (I've seen lots of changes for the combo-box in the 3.1 branch).

Anyway, with the manifest provided in my last PR it works any way.

**Comment by victorlevasseur** [comment]
Ok, thank you. I will give wxWidgets 3.1 a try (on Windows only, on Linux
the version depends on the distro)
