### ISSUE TITLE
Release a small bugfix version for Windows only

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#276]
A lot of users currently have problems with the manifest (they can't edit the text objects and some can't open a scene without a crash).

**Comment by victorlevasseur** [comment]
Bump @4ian 
I can do it myself too if you don't have the time. However, I can't change the website link (maybe replace the lastest binaries for Windows by the small hotfix ?)

**Comment by 4ian** [comment]
If you can generate a working updated version with the fix that would be
handy! :) I won't be able to release a new version before next week.
