### ISSUE TITLE
Question - GD and RPG Maker

### ISSUE THREAD

**Issue by kholyphoenix1** [4ian/GD#285]
Hello!

I wonder if you can create a game similar to RPG Maker MV.
I want to design the camera on top of the character.

Thanks!!

Image:
https://lh3.googleusercontent.com/dmonOKtcLavp-a3bQC-pZzu7xSSZKXIQLflawWRbTjcBxQayBBLZI4ach1qkmPyZYvw=h900

**Comment by victorlevasseur** [comment]
Yes, you can do it with GDevelop. However, it will obviously require a bit
more work than with RPG Maker as GDevelop is designed to allow the creation
of many games types.

**Comment by kholyphoenix1** [comment]
I understand. Thank you for your help!
