### ISSUE TITLE
Font size wrong on high DPI screen

### ISSUE THREAD

**Issue by demar42** [4ian/GD#295]
Hi there,

I have a MacBook Air retina running windows with a resolution of 2560 x 1600. When I open GDevelop, all the font sizes seem wrong and don't fit in their boxes.

I have attached an image to show what it looks like
![image](https://cloud.githubusercontent.com/assets/16697489/18222959/785fa6cc-71fb-11e6-8bd3-19ba85c1640c.png)

Do you know what I could change (computer/gdevelop settings) to make this look right? I really want to get stuck into using GDevelop as it seems like a really good game maker

Thanks in advance
demar42

**Comment by victorlevasseur** [comment]
Try to do this : https://support.microsoft.com/en-us/kb/2900023

**Comment by victorlevasseur** [comment]
No answers, I close this for the moment
