### ISSUE TITLE
Select the starting animation (and frame ?) of a sprite on the scene

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#296]

**Comment by 4ian** [comment]
Changing the start animation is already feasible for each instance on the scene right? (using the properties of the instance)
Do you mean an option to change the default animation if nothing is specified (which is animation 0 for now)?

**Comment by victorlevasseur** [comment]
Oh, did watched the property panel :S

**Comment by 4ian** [comment]
Maybe that's too hidden ;)

**Comment by victorlevasseur** [comment]
There's no option to set the starting image of the starting animation
