### ISSUE TITLE
Selection is not properly deleted in scene editor (master branch)

### ISSUE THREAD

**Issue by 4ian** [4ian/GD#302]
@victorlevasseur There is a regression in master that looks related to `InitialInstancesContainer`. If you open a scene editor, select a bunch of objects with the mouse and then delete them, the wrong objects are deleted (some of the selection are still there, some that are not in the selection are deleted).

I've run a git bisect and [this commit](https://github.com/4ian/GD/commit/5aa30efa52fee08fd7e8c83be799cfa2eca841b8) introduces the bug:
````
~/Projects/F/GD   5aa30ef... | bisect  git bisect bad
5aa30efa52fee08fd7e8c83be799cfa2eca841b8 is the first bad commit
commit 5aa30efa52fee08fd7e8c83be799cfa2eca841b8
Author: Victor Levasseur <victorlevasseur52@gmail.com>
Date:   Wed Sep 14 11:52:40 2016 +0200

    Improve InitialInstancesContainer code

    Add tests for InitialInstancesContainer

:040000 040000 48a593620e86b6fcb5dcd6f86c1002b6406a8e4f 45e0de8e566eed74c9d50b9327029720802a1aca M     	Core
:040000 040000 9e6c6285f42856511097adbc80ed42c353b3a565 e28478af445080cfe17b656cc08fd966e04e4a46 M     	GDCpp
:040000 040000 4a1781881815518823316f6cbf0a5d2008e0bec2 bb6f8cd47f4bd0ab4a2249c0d8d9c8b431a8822b M     	IDE
````

I'm looking at the issue - maybe we could add a test for it once we have spotted the bug ;)

**Comment by victorlevasseur** [comment]
Found the issue. ```remove_if``` swaps the elements to be deleted at the end of the list. As ```InitialInstances``` are stored directly in the list. Their addresses change and further pointer comparison gives an undefined result. Will fix it soon.

**Comment by 4ian** [comment]
Done :) Let me know what you think: https://github.com/4ian/GD/pull/303
