### ISSUE TITLE
Custom fonts crashes with gd::SFMLFileStream

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#315]
Because the stream should be kept alive while the sf::Font is used (it's a streaming object).

**Comment by 4ian** [comment]
This is a regression in compiled native games, IDE or both?

**Comment by victorlevasseur** [comment]
It's a regression in IDE (the gd::FileStream is not kept alive long enough)

Le sam. 19 nov. 2016 19:44, Florian Rival <notifications@github.com> a
écrit :

**Comment by 4ian** [comment]
@victorlevasseur Thanks for solving this! When you push something directly to master, could you please just post a message in the issue to tell if it's fixed and in which commit?
