### ISSUE TITLE
Can't open my project.

### ISSUE THREAD

**Issue by Ryuto16** [4ian/GD#316]
When i try to open my project (gdg), it open in the left window, but i can't see anything more :( 

(sorry, i'm new and i can't find a solution)
(yep, english is not my native lenguish, sorry for that too)
![d](https://cloud.githubusercontent.com/assets/23569043/20454057/104a5d0a-ae0c-11e6-8596-c546333f77c2.png)

**Comment by Lizard-13** [comment]
You have to double click a scene (i.e. "Nueva Escena") to edit it :wink:
