### ISSUE TITLE
ExpressionParser in external events

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#318]
I wonder if it's possible to use ExpressionParser with an external event (or nothing) instead of a ```gd::Layout```.

What I want to do is to write a custom callback to get all the _(...) string expressions from the expressions/strings from all the events of a project. I already browse the whole project by using a ```ArbitraryEventWorker``` on all the scene's events and external events. But, then, I would like to fetch all the _(...) expressions from the expressions of the actions/conditions/variable child name... I currently use a regex thanks to wxWidgets but I would like to use a more appropriate solution.

*You can guess what I'm doing :p, and it already works on the ```feature/string-format``` branch of my fork (the branch is named after the first feature that I added to the branch.*

**Comment by 4ian** [comment]
Closing this as it seems it's not relevant anymore :)
