### ISSUE TITLE
Remove AppVeyor from Github

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#328]
It's useless and errors all PR.

**Comment by 4ian** [comment]
True! I never took the time to fix it, actually it broke during an AppVeyor update: https://twitter.com/Game_Develop/status/754636665952567296?lang=en

I think it can be something as simple as a directory missing in the PATH

**Comment by 4ian** [comment]
I've made a few tests, git was missing from the PATH. After adding it it's building but tests are still not launched. I've connected with RDP to the instance and the MinGW dlls are not properly copied. Tried to copy them manually from the MinGW `bin` folder but it's still failing with `The procedure entry point _ZSt24__throw_out_of_range_fmtPKcz could not be located in the dynamic link library `.
I wonder if there is a conflict between 32/64 bits versions of MinGW

**Comment by victorlevasseur** [comment]
Maybe, is GDevelop built in 32 bits?

**Comment by 4ian** [comment]
Not sure, I think that's the case while inspecting the GDCore_tests.exe file. I'm going to try to use MinGW64

**Comment by 4ian** [comment]
Done! :)
