### ISSUE TITLE
Dragonbones file support

### ISSUE THREAD

**Issue by blurymind** [4ian/GD#334]
What is dragonbones - A free alternative to spine2d. It allows for cutout/2d mesh deform animation that has huge gains on animation size . Also allows for things like swapping body parts or overwriting movement via code.

It also allows:
- reusing the same animation clip on multiple game characters with different graphics
- big gains on local and virtual memory, gains in framerate
- Time saver in producing the actual animated assets
- Both editor and runtime are free 
- Smooth interpolation between animation clips
- smooth inbetweens , regardless of the framerate

www.dragonbones.com
https://www.youtube.com/watch?v=YO7JzI-f7sc

Spine costs 300$ for using their runtime - even if you dont have the editor
Dragonbones has all the same features, but is free

Dragonbones has a pixi.js runtime:
https://github.com/DragonBones/DragonBonesJS/tree/master/Pixi

which potentially makes it easy to implement in GD

Please implement support for dragonbones animation data support in gamedevelop. It will be a game changer for developing web and android games

**Comment by blurymind** [comment]
Dragonbones animation data can now also be created via Blender and Flash - 
https://github.com/ndee85/coa_tools/issues/26
You will also find info on the dragonbones json file structure in the link too.

so those who dont like using the official free editor or the adobe animate/flass plugin, can use blender.

**Comment by 4ian** [comment]
Looks nice indeed! For now no plan to integrate it very soon but that may be useful one day so I've added it to the roadmap ideas (see https://trello.com/c/KNwIBNen/39-support-for-spine-dragonbones-skeletal-animation-files)

**Comment by blurymind** [comment]
Thank you!

Its worth noting the cocos has built in support for dragonbones now. DB and Spine assets are supported in cocos creator natively - with no additional need to install runtimes

If you plan to further support cocos for gdevelop, all you would need to do is expose the api to gdevelop.

I personally dont mind the bigger download size at all and would love it if we start getting the editor prepackaged with cocos as the main option

**Comment by blurymind** [comment]
It looks like @Lizard-13 implemented this now, so I can close the request.

Will have to test it out in the weekend :)

**Comment by Lizard-13** [comment]
You can reopen it so I can feel bad for not porting it yet :)

**Comment by blurymind** [comment]
With the current arrangement I think we need to keep this issue closed, but still have it as a card on trello- as it is not really done if the gd5 users have no access to it

**Comment by 4ian** [comment]
Let's make a new card for it on Trello in the "Ideas for the game engine 💡" column.
