### ISSUE TITLE
Plante à l'ouverture d'un projet

### ISSUE THREAD

**Issue by Marc34** [4ian/GD#337]
Bonjour,

J'ai compilé GD, et il se bloque lorsque l'on ouvre un nouveau projet ou un exemple. J'ai le message suivant :

Bool attribute "folderProject" not found, returning 0Bool attribute "updateIfNotVisible" not found, returning 1Bool attribute "updateIfNotVisible" not found, returning 1Bool attribute "updateIfNotVisible" not found, returning 1Bool attribute "updateIfNotVisible" not found, returning 1Child effects not found in SerializerElement::GetChild
Child effects not found in SerializerElement::GetChild
The program 'GDIDE' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 161 error_code 10 request_code 2 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by victorlevasseur** [comment]
Même problème que #338.
