### ISSUE TITLE
[QUESTION] Multiple levels in platformer?

### ISSUE THREAD

**Issue by samvdkris** [4ian/GD#342]
Not a bug, but a question. If I make a platformer the objects and events are connected to a scene. Is there a way to make multiple levels (that use the objects and events) without having to copy them all the time?

**Comment by 4ian** [comment]
Either make multiple scenes with a Link event to import events from the original scene, or have a single scene creating objects from external layout (each external layout is a level and you create the objects at the beginning according to a global variable value, set when selecting the level in the menu for example).

The second alternative is better as it's lightweight (code for the scene is not duplicated) but needs a bit more work :)

**Comment by samvdkris** [comment]
Thanks a lot for the quick and useful answer! I'll try the external layout thing (and the other one if that somehow doesn't work).

Again, thanks a lot! :)
