### ISSUE TITLE
Where is the executeable file?

### ISSUE THREAD

**Issue by JebusKD** [4ian/GD#345]
I am so sorry or being stupid if it is somewhere clear. But where is the file to open the program?

**Comment by victorlevasseur** [comment]
Windows or Linux ?

**Comment by JebusKD** [comment]
Windows

**Comment by 4ian** [comment]
Once you've compiled it, it will be in Binaries/Output/Release_Windows
See this to compile: http://4ian.github.io/GD-Documentation/GDCore%20Documentation/setup_dev_env.html

You might not want to actually do it but simply download the official distribution here: http://compilgames.net

**Comment by victorlevasseur** [comment]
The installer provided on the official website should have created a link
to launch the program (the executable is GDIDE.exe and is where you decided
to install the program).
