### ISSUE TITLE
event / read from file

### ISSUE THREAD

**Issue by Translator5** [4ian/GD#346]
Hi,
I would like to read a text from a file and store it as a scene-variable.
I got the event, set all up, but the variable still do not change.

This is my event: [File: "file.txt" Group: "GROUP1" Scene: "distro"]
The action do work properly.

Here is the file.txt I want to read from.
`<?xml version="1.0" encoding="ISO-8859-1" ?>`
`<GROUP1 texte="LinuxMint" />`

Why do this not work?

**Comment by Translator5** [comment]
Got it :smile: 

by the way -> nice project!

**Comment by 4ian** [comment]
Thanks :) For further questions about using the software, you can ask on the user forum: http://forum.compilgames.net/ 😄
