### ISSUE TITLE
[solved] javascript code repeat each frame

### ISSUE THREAD

**Issue by Elmapul** [4ian/GD#348]
as said above, the javascript code is set to run in each frame, as a result, in an code like:

var test=0;
test++;
console.log(test);

the variable will never increase futher than 1.

add an option to run once, each frame or when an specific condition (event) is fulfilled.

as it curently is, its almost useless.

**Comment by 4ian** [comment]
The code is working properly, as you're declaring a new variable at each frame using `var test = 0`.
To store a variable, you can attach it to `runtimeScene` object:

```
runtimeScene.test = runtimeScene.test || 0; //This will set the variable to 0
runtimeScene.test++;
console.log(runtimeScene.test);
```

or more complex objects: 

```
if (!runtimeScene.playerInformation) {
  runtimeScene.playerInformation = { name: "John" };
}

console.log(runtimeScene.playerInformation.name);
```

**Comment by Elmapul** [comment]
this code was just an test/example.
i don't know if this will solve the problem in the future (eg: if i want to import an larger library, doing that will cost too much time)

but i will use this solution for ow.

**Comment by 4ian** [comment]
If it's working for you, it is ok to close the issue? Let me know if you are still unsure.

**Comment by Elmapul** [comment]
i guess you can close, i have to set my mind arround it.
i mean, for games, most of the functions you want to repeat at each frame.

and using and "if (!runtimeScene.playerInformation){"
if/else i can ditch everycode that i dont want to run, i dont know how javascript compiler/interpreter works, if this extra code will be sent only if the condition is true.

i'm not using gDevelop as much as i think, so it will take sometime to figure out if this cause any problem.
