### ISSUE TITLE
Can't install on Kubuntu 64 bits

### ISSUE THREAD

**Issue by Caloxeno** [4ian/GD#350]
As said in the GDevelop's download page (http://compilgames.net/main-es.html), I put the following code in a terminal in order to install:

sudo add-apt-repository ppa:florian-rival/gdevelop
sudo apt-get update
sudo apt-get install gdevelop

But after entering the last line of code, it says:

E: Unable to locate package gdevelop

Any ideas on how to fix this? Thanks.

**Comment by Translator5** [comment]
please use terminal and afterwards host it on gisthub ... than send us a url ...

**Comment by ilyasofficial1617** [comment]
i experienced this too 
at lubutntu
based on ubuntu 17.04 zesty

is there any deb file that can be downloaded manually ?

**Comment by Translator5** [comment]
[launchpad.net](https://launchpad.net/~florian-rival/+archive/ubuntu/gdevelop/+packages)

> Package files

    gdevelop_4.0.92004-1~xenial.debian.tar.gz (2.0 KiB)
    gdevelop_4.0.92004-1~xenial.dsc (1.6 KiB)
    gdevelop_4.0.92004-1~xenial_amd64.deb (58.2 MiB)
    gdevelop_4.0.92004.orig.tar.gz (74.5 MiB)

**Comment by Halamix2** [comment]
Same here, [PPA](https://launchpad.net/~florian-rival/+archive/ubuntu/gdevelop) has no support for Ubuntu 16.10 and 17.04, that's why installation is failing, only versions from 14.04 to 16.04 are supported without manually editing repos list. (Also it contains older 4.0.92 version)

**Comment by Halamix2** [comment]
Also connected to #339

**Comment by VR51** [comment]
Looks like the last Ubuntu release of GDevelop was for Xenial.

You can build it from the source files. Took an hour for the build to complete. The general path is:

1) Install CMake, its dependencies and QT. Both are in the K/Ubuntu software repositories 
2) Install the latest version of WxWidgets. The official Ubuntu repo release of WxWidgets might not be good enough for GDevelop to build successfully. I had to use the release from http://wxwidgets.org/downloads/
3) Download GDevelop from https://github.com/4ian/GD. Extract the files.
4) Use CMake-QT to configure and generate the GDevelop install file. Tell cmake where it can find the source files to make and to put cmake's output into the 'binaries' directory of the GDevelop directory.
5) Run 'sudo make install' from the binaries directory.

You can now use gdevelop.

Errors were thrown by cmake when I used the Ubuntu provided wxwidgets. Only warnings about deprecated functions were thrown after the official wxwidgets files were installed.

You might also need to install freeglut3 and libalut-dev.

**Comment by 4ian** [comment]
Awesome! I don't now if there is any way you could build a PPA from this?
I made a script for this a while ago that I used to build my PPA: https://github.com/4ian/GD/blob/master/Binaries/Packaging/PackageForUbuntu.sh

The GPG public key must be changed and the version number too, otherwise it should work.

**Comment by Halamix2** [comment]
I was able to build GD (`cmake . ; make`) , and I'll try to fork GD and set Travis to output .deb packages (maybe even push them to PPA)? http://travis.debian.net/

**Comment by VR51** [comment]
@Halamix2 I've seen Travis mentioned several times over the years but never bothered to find out what it is. Now I know what it is I think I quite like it.

@4ian looks like Halamix2 has this covered.

**Comment by Halamix2** [comment]
Or we can use somehow https://docs.travis-ci.com/user/deployment/launchpad/ , previous travis method probably require having separate /debian/ branch (and some edits in travis.yml that I'm too scared to make)

**Comment by 4ian** [comment]
Yep, OpenSUSE Build Service looks nice and there is a build script here: https://github.com/4ian/GD/blob/master/Binaries/Packaging/PackageForOBS.sh made by @victorlevasseur 😃 
Give it a try to see if you can get it working :)

**Comment by Halamix2** [comment]
I am unable to create package named GDevelop, perhaps because [one is already there](https://build.opensuse.org/package/show/home:victorlevasseur/gdevelop), I'll email him if he can add Ubuntu .deb builds to his project.

**Comment by 4ian** [comment]
Closing this as I now recommend to use GDevelop 5 which should work properly on any recent distro :)
