### ISSUE TITLE
Crashing when opening new project, Linux (4.11.6-3-ARCH)

### ISSUE THREAD

**Issue by nannerpusser** [4ian/GD#356]
Currently getting similar, mostly identical crash to #343  but on Arch Linux (4.11.6-3-ARCH # 1 SMP PREEMPT Thu Jun 22 12:21:46 CEST 2017 x86_64 GNU/Linux). Debugging with my limited skills, can always re-exec with the '--noCrashCheck' flag, but still crashing when opening a new project. Also can configure options, but Language is an issue, constant error message, but not critical. I cannot force with "--lang=en_GB" flag, nor does changing it to "US" or my system LANG seem to matter. 

gdevelop --version = **new-ide-beta1-16-g9fbc4613a** (straight from the AUR, pulls from git)

Here's the dump, don't have any kind of "happy crash" dialog here with Report option:

> Jun 25 11:01:05 **** systemd[1]: Started Process Core Dump (PID 23085/UID 0).
> Jun 25 11:01:05 **** kernel: GDIDE[23067]: segfault at 3f0 ip 000055ef67b9e8f4 sp 00007ffe8e7a5e70 error 4 in GDIDE[55ef67a21000+3ae000]
> Jun 25 11:01:01 **** systemd-coredump[23021]: Process 22961 (GDIDE) of user 1000 dumped core.
> 
>                                                    Stack trace of thread 23067:
>                                                    #0  0x000055ef67b9e8f4 _ZN14GDevelopIDEApp20OnUnhandledExceptionEv (GDIDE)
>                                                    #1  0x00007fd51698e488 _Z7wxEntryRiPPw (libwx_baseu-3.0.so.0)
>                                                    #2  0x000055ef67b26367 main (GDIDE)
>                                                    #3  0x00007fd5133d343a __libc_start_main (libc.so.6)
>                                                    #4  0x000055ef67b2eeda _start (GDIDE)
>                                                    
>                                                    Stack trace of thread 23077:
>                                                    #0  0x00007fd5107a839d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
>                                                    #1  0x00007fd506ba02fb n/a (radeonsi_dri.so)
>                                                    #2  0x00007fd506ba0037 n/a (radeonsi_dri.so)
>                                                    #3  0x00007fd5107a2297 start_thread (libpthread.so.0)
>                                                    #4  0x00007fd5134a025f __clone (libc.so.6)
>                                                    
>                                                    Stack trace of thread 23078:
>                                                    #0  0x00007fd5107a839d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
>                                                    #1  0x00007fd506ba02fb n/a (radeonsi_dri.so)
>                                                    #2  0x00007fd506ba0037 n/a (radeonsi_dri.so)
>                                                    #3  0x00007fd5107a2297 start_thread (libpthread.so.0)
>                                                    #4  0x00007fd5134a025f __clone (libc.so.6)
>                                                    
>                                                    Stack trace of thread 23080:
>                                                    #0  0x00007fd5107a839d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
>                                                    #1  0x00007fd506ba02fb n/a (radeonsi_dri.so)
>                                                    #2  0x00007fd506ba0037 n/a (radeonsi_dri.so)
>                                                    #3  0x00007fd5107a2297 start_thread (libpthread.so.0)
>                                                    #4  0x00007fd5134a025f __clone (libc.so.6)
>                                                    
>                                                    Stack trace of thread 23082:
>                                                    #0  0x00007fd5134962bd poll (libc.so.6)
>                                                    #1  0x00007fd50edb5bf9 n/a (libglib-2.0.so.0)
>                                                    #2  0x00007fd50edb5d0c g_main_context_iteration (libglib-2.0.so.0)
>                                                    #3  0x00007fd50edb5d51 n/a (libglib-2.0.so.0)
>                                                    #4  0x00007fd50eddcac5 n/a (libglib-2.0.so.0)
>                                                    #5  0x00007fd5107a2297 start_thread (libpthread.so.0)
>                                                    #6  0x00007fd5134a025f __clone (libc.so.6)
>                                                    
>                                                    Stack trace of thread 23083:
>                                                    #0  0x00007fd5134962bd poll (libc.so.6)
>                                                    #1  0x00007fd50edb5bf9 n/a (libglib-2.0.so.0)
>                                                    #2  0x00007fd50edb5f92 g_main_loop_run (libglib-2.0.so.0)
>                                                    #3  0x00007fd50c167426 n/a (libgio-2.0.so.0)
>                                                    #4  0x00007fd50eddcac5 n/a (libglib-2.0.so.0)
>                                                    #5  0x00007fd5107a2297 start_thread (libpthread.so.0)
>                                                    #6  0x00007fd5134a025f __clone (libc.so.6)
>                                                    
>                                                    Stack trace of thread 23076:
>                                                    #0  0x00007fd5107a839d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
>                                                    #1  0x00007fd506ba02fb n/a (radeonsi_dri.so)
>                                                    #2  0x00007fd506ba0037 n/a (radeonsi_dri.so)
>                                                    #3  0x00007fd5107a2297 start_thread (libpthread.so.0)
>                                                    #4  0x00007fd5134a025f __clone (libc.so.6)
>                                                    
>                                                    Stack trace of thread 23079:
>                                                    #0  0x00007fd5107a839d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
>                                                    #1  0x00007fd506ba02fb n/a (radeonsi_dri.so)
>                                                    #2  0x00007fd506ba0037 n/a (radeonsi_dri.so)
>                                                    #3  0x00007fd5107a2297 start_thread (libpthread.so.0)
>                                                    #4  0x00007fd5134a025f __clone (libc.so.6)
>                                                    
>                                                    Stack trace of thread 23081:
>                                                    #0  0x00007fd5107a839d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
>                                                    #1  0x00007fd506ba02fb n/a (radeonsi_dri.so)
>                                                    #2  0x00007fd506ba0037 n/a (radeonsi_dri.so)
>                                                    #3  0x00007fd5107a2297 start_thread (libpthread.so.0)
>                                                    #4  0x00007fd5134a025f __clone (libc.so.6)
> 

The radeon driver seems out of place, not sure why it's in the trace (I am new to bug reporting, debugging, tracing, etc.) I moved this to a new Issue since it's not Mac-related.

**Comment by 4ian** [comment]
Hi @nannerpusser. The crash when creating/opening a new project is due to the branch being named `new-ide-beta1-16-g9fbc4613a`, which is not following "major.minor.revision.patch" scheme and making the code discovering the version number crash.
Could you try again with version tagged 4.0.94? I've also created a tag [`4.0.95`](https://github.com/4ian/GD/releases/tag/4.0.95) to avoid having users relying on new-ide-beta1 tag.

**Comment by nannerpusser** [comment]
You are 100% correct. Rather than use the AUR build I added the repo to pacman.conf and installed that way, and it seems to work fine now. A couple IDE errors popped up when I closed projects, but this time I did get the option to attach a txt file report. It wasn't anything critical, I think it didn't like my build and tmp dirs I defined. If it persists I'll bug you with another issue.

Out of curiosity, are you not the maintainer of the AUR PKGBUILD? I assumed that the devs/you had the Arch Repo and did the PKGBUILD.

**Comment by 4ian** [comment]
Sweet :) 

> Out of curiosity, are you not the maintainer of the AUR PKGBUILD? I assumed that the devs/you had the home_victorlevasseur_Arch_Extra repo and did the PKGBUILD.

I'm not the maintener of the PKGBUILD, it's an external contributor doing it :) 
I must admit that it's a bit hard for me to maintain full compatibility with Linux and the different distro (hence the bugs you've stumbled upon), things are not properly polished. I'm mainly developing on OS X and testing on Windows as much as I can.
Hopefully this should be a lot better with the upcoming GDevelop 5, which will is based on a brand-new editor and which will have full compatibility with Windows/OS X and any recent Linux distro (and even web browser later! :)).

Let me know in any case if there is something else that is blocking for you.
