### ISSUE TITLE
Default "Apply changes to whole animation"

### ISSUE THREAD

**Issue by Lizard-13** [4ian/GD#357]
Those buttons (apply points/masks changes to whole animation) active by default gives a lot of problems 😡 . I suggest to change them to false, at least the points one :)

**Comment by 4ian** [comment]
Is true that I often erase points using these, but on the other hand newcomers may be confused when they add a point ("why is my point not at the proper position when the animation is playing?".
So not sure what the best solution is :/

**Comment by Lizard-13** [comment]
What about two buttons?, one for creating points (default true) and the other to modify them (false)? This way, when you create a new point it's created at every frame, but modify them only in the current frame by default. Maybe a forum topic with suggestions about the events and objects editors should be started if the idea to rewrite these editors keep going 😃

**Comment by 4ian** [comment]
Could you make a quick sketch/mockup of your idea? I'll work on a new editor for the points/collision hitboxes in the new IDE so any idea is welcome :)

**Comment by Lizard-13** [comment]
4iaaaaaan, another victim: http://forum.compilgames.net/viewtopic.php?f=19&t=9416&p=63678#p63670
Ok, now we have the new IDE, so I could check it out :D

**Comment by 4ian** [comment]
Will close this as it's now quite different in GDevelop 5, hopefully it's more clear! Feel free to open another different issue if needed :)
