### ISSUE TITLE
Can't build GD anymore

### ISSUE THREAD

**Issue by Lizard-13** [4ian/GD#366]
After the commit 6d5e4e388ff8d3f5b258aa4f723512ff4b89b0c0 my compilations fail, deleted the entire directory, cloned the repository again and still fails with errors related to undefined references to DependenciesAnalyzer functions. You moved the DependenciesAnalyzer from Cpp to Core, maybe a CMake file gets out of date?, I have no idea how cmake files work :(

EDIT: It's compiling ok in my Ubuntu, the problem is Windows

**Comment by 4ian** [comment]
What is the exact error? Can you copy paste here? :) Otherwise it's hard to guess what the problem can be :)

**Comment by Lizard-13** [comment]
Sure, sorry:

> [ 38%] Building CXX object GDCpp/CMakeFiles/GDCpp.dir/GDCpp/IDE/Dialogs/RenderDialog.cpp.obj
[ 38%] Linking CXX shared library ..\..\Output\Release_Windows\GDCpp.dll
CMakeFiles\GDCpp.dir/objects.a(CommonInstructionsExtension.cpp.obj):CommonInstructionsExtension.cpp:(.text+0xa69a): undefined reference to `DependenciesAnalyzer::DependenciesAnalyzer(gd::Project&, gd::ExternalEvents&)'
CMakeFiles\GDCpp.dir/objects.a(CommonInstructionsExtension.cpp.obj):CommonInstructionsExtension.cpp:(.text+0xa6ca): undefined reference to `DependenciesAnalyzer::ExternalEventsCanBeCompiledForAScene()'
CMakeFiles\GDCpp.dir/objects.a(CommonInstructionsExtension.cpp.obj):CommonInstructionsExtension.cpp:(.text+0xa724): undefined reference to `DependenciesAnalyzer::~DependenciesAnalyzer()'
CMakeFiles\GDCpp.dir/objects.a(CommonInstructionsExtension.cpp.obj):CommonInstructionsExtension.cpp:(.text+0xa769): undefined reference to `DependenciesAnalyzer::~DependenciesAnalyzer()'
CMakeFiles\GDCpp.dir/objects.a(CommonInstructionsExtension.cpp.obj):CommonInstructionsExtension.cpp:(.text+0xa7cb): undefined reference to `DependenciesAnalyzer::~DependenciesAnalyzer()'
c:/mingw32/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: CMakeFiles\GDCpp.dir/objects.a(CommonInstructionsExtension.cpp.obj): bad reloc address 0x2 in section `.text$_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EED1Ev[__ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EED1Ev]'
collect2.exe: error: ld returned 1 exit status
GDCpp\CMakeFiles\GDCpp.dir\build.make:3519: recipe for target '../Output/Release_Windows/GDCpp.dll' failed
mingw32-make[2]: *** [../Output/Release_Windows/GDCpp.dll] Error 1
CMakeFiles\Makefile2:709: recipe for target 'GDCpp/CMakeFiles/GDCpp.dir/all' failed
mingw32-make[1]: *** [GDCpp/CMakeFiles/GDCpp.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by 4ian** [comment]
I forgot to add GD_CORE_API in DependenciesAnalyzer declaration so that dllexport annotation is added on Windows.
So this symbol was not exposed in GDCore.dll and GDCpp.dll could not find it at linking time.

I made the fix here: https://github.com/4ian/GD/commit/0c688e714a8792ddfe5f1f19a0432345ae88df64 could you try again? :)

**Comment by Lizard-13** [comment]
Yup, fixed :D
