### ISSUE TITLE
Question - Develop games in 3D

### ISSUE THREAD

**Issue by kholyphoenix1** [4ian/GD#368]
Hello.
Are the developers of this engine interested in enabling the development of 3D games?

Thank you!

**Comment by 4ian** [comment]
Hi, that would be awesome but making a 3D engine is a really huge task and the way 3d games are created is a bit different from 2d games.
The best way would be to be integrated with some engine like Unity or Unreal Engine while still providing the same easy-to-use interface for events, objects creation...

That's not something that is planned for now, I would need help from developers that are familiar with 3d engines.

**Comment by kholyphoenix1** [comment]
Thanks for the clarification. The 'GD' is a fantastic engine and I very much believe in its power. Congratulations!

**Comment by 4ian** [comment]
Thanks :) Closing this issue for now but you can go on the forum for any other question :)

**Comment by issamgithub** [comment]
Hopefully you can add 3D features like in version 4.

**Comment by 4ian** [comment]
Please vote/comment for this here: https://trello.com/c/EiG3yzhM/105-add-3d-box-objects  :)
