### ISSUE TITLE
libwx_gtk2u_html erro?

### ISSUE THREAD

**Issue by kholyphoenix1** [4ian/GD#374]
Hello, 

OpenSuse 42.3 erro with Gdevelop...

`Unable to launch GDevelop, a unknown error happened! Here is the full error message: 
 ./GDIDE: relocation error: ./libGDCore.so: symbol _ZThn664_N13wxHtmlListBox10RefreshAllEv, version WXU_3.0 not defined in file libwx_gtk2u_html-suse.so.3 with link time reference
`

Gnome-Terminal:

`linux@linux-a02n:~> gdevelop
./GDIDE: relocation error: ./libGDCore.so: symbol _ZThn664_N13wxHtmlListBox10RefreshAllEv, version WXU_3.0 not defined in file libwx_gtk2u_html-suse.so.3 with link time reference
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
`

**Comment by 4ian** [comment]
Closing this as I now recommend to use GDevelop 5 which should work without any issues :)
