### ISSUE TITLE
Making an active preview inaccessible.

### ISSUE THREAD

**Issue by agameraaron** [4ian/GD#377]
I somehow made the preview inaccessible. The scene (and all other) tabs become unresponsive and the user is left unable to save their project! File simply says "Please stop the preview before continuing".

Conditions to replicate:
I started editing the event sheet and it must have changed the tabs at the top. This was while a preview was still active.

![cannot access scene tab](https://user-images.githubusercontent.com/12471157/29820149-b0bab05c-8c80-11e7-8660-641cb00fa5d7.png)

**Comment by 4ian** [comment]
Click on Scene tab in the ribbon then on "Stop The Preview" button? :)

**Comment by agameraaron** [comment]
The scene tab was unresponsive. It did nothing when clicked on.

**Comment by 4ian** [comment]
Strange. Can you reproduce the same bug again now?

**Comment by agameraaron** [comment]
It would appear I was clicking on the wrong 'scene' tab this whole time. There is one above (File, Projects, Images bank, **Scene**) and one below (**Scene**, Events). I was trying to click the one above. That's a bit confusing. When people told me to click the 'scene' tab, I was technically doing that, just the wrong one.

**Comment by Lizard-13** [comment]
I think the magic word in 4ian's first comment is "ribbon", but it can be a bit confusing indeed :)

**Comment by agameraaron** [comment]
Ooh, okay, gotcha. I was clicking on the ribbon's Scene button. I will close this as it was a user error on my part. If I think of a good design that might infer what to do when in the same situation, I will put it under feature request.

**Comment by Lizard-13** [comment]
@4ian, could it be possible to change the name of "Scene" in the ribbon into "Preview" while you are doing a preview?, this way the users will se this big "Preview" tab on the top and then the "Stop preview" button 🤔

**Comment by 4ian** [comment]
@agameraaron In the upcoming GDevelop 5, I've split scene and events in two separate tabs.
And the preview runs in a separate window so it's not blocking the whole editor so this problem should not appear. See this screenshot:
![image](https://user-images.githubusercontent.com/1280130/29923068-6fd855ec-8e58-11e7-9189-70b9d766a819.png)

Do you think it's better?

@Lizard-13 I think it would add even more confusion. It's not a common pattern to have ribbon tab changing its name. :/ 
I'm quite confident the next major version (GDevelop 5) won't have this problem. :)

**Comment by agameraaron** [comment]
Looks great; looking forward to the next version! The new interface looks to be very user friendly.

**Comment by blurymind** [comment]
I feel that the new interface is built more for a mobile device and would not look as good on a bigger screen desktop machine screen as the old one with these giant buttons and tabs . They take away space from the level editor and event sheet frame. There is also a lot of wasted empty space above the tabs in the screenshot, but I am assuming that is because it is a WIP and it might get populated as the editor matures more. :) I am judging it too early
