### ISSUE TITLE
VersionPriv.h

### ISSUE THREAD

**Issue by AlihassanProgrammer** [4ian/GD#379]
VersionPriv file miss from the project. Without this file GD terminate and throws 50 + errors. 
![image](https://user-images.githubusercontent.com/11745671/29920389-c12a72be-8e66-11e7-9bdd-b8ebb82954ec.png)
![image](https://user-images.githubusercontent.com/11745671/29920363-a1ab4300-8e66-11e7-9b33-71b9e88023a4.png)

**Comment by 4ian** [comment]
Code::Blocks projects are outdated and should be removed (I keep them in case I have to tweak an existing dialogs made with wxSmith, the RAD tool integrated in Code::Blocks).
Don't use them: instead, compile with CMake as explained here: http://4ian.github.io/GD-Documentation/GDCore%20Documentation/setup_dev_env.html 😃

**Comment by 4ian** [comment]
(VersionPriv.h is generated by Cmake during the build). Note that CMake is maybe able to generate Code::Blocks projects. But I would recommend starting simple and compile using CMake + makefiles as explained in the doc ;)

**Comment by AlihassanProgrammer** [comment]
Thanks sir
