### ISSUE TITLE
Can't install GDevelop from Fedora Repo

### ISSUE THREAD

**Issue by briguyjm** [4ian/GD#380]
I am trying to install GDevelop using the Fedora repo. I add the repo, run `sudo dnf install gdevelop` and then get the following error: 

    Error:
     Problem: conflicting requests
      - nothing provides libGLEW.so.1.13 needed by gdevelop-4.0.94-2.1.i686
      - nothing provides libGLEW.so.1.13()(64bit) needed by gdevelop-4.0.94-2.1.x86_64

I have installed `libGLEW`, `glew-devel`, and `glew`, for both the `x86_64` and the `i686` versions. I am using Fedora 26.

Using the RPM file and the `rpm -ivh` command yields similar results.

**Comment by 4ian** [comment]
Closing this as I now recommend to use GDevelop 5 which should work on Fedora without issues :)
