### ISSUE TITLE
Blockly for events system

### ISSUE THREAD

**Issue by pavi2410** [4ian/GD#386]
Hello @4ian, would you please consider using Blockly as the event system. It is very similar to Scratch and App Inventor and is very easy to learn and use.

**Comment by 4ian** [comment]
It's a nice system too indeed. I still think that events are a bit more efficient when working on large games (but I've not used blockly a lot so I may be mistaken). For example, events support copy-paste, moving actions or conditions, copying/replacing parameters and I'm not sure if you can do this efficiently with Blockly.
Also it seems that events takes less space on the screen so you can see more thing compared to blocks that takes a lot a space to express simple things.
Even for doing simple mathematical operations, using Blockly you have to use the blocks. It's nice to get started, but I highly doubt you can be proficient by doing this... So in the end I'm afraid that it would be more an obstacle for users than a benefit.

Technically, such a feature would need to implement both support for events and Blockly in GDevelop, to have a compatibility/translations between them and to remake/adapt all the code generation with Blockly. All events, actions, conditions and expressions would need to be converted to blockly - and I'm not even sure how parameters types supported by GDevelop can be handled by Blockly.

I've mostly based this answer on what I saw here https://developers.google.com/blockly/ so I may have missed more advanced features. Let me know in this case :)

**Comment by blurymind** [comment]
please keep the current event sheet system. It has better layout and
organisation.
The blockly approach with the puzzle pieces is slower to learn and use. I
tried it

**Comment by pavi2410** [comment]
@blurymind, I find the current event system to be inefficient as you to type everything to do simple things and it has some limited drag and drop functionality. Writing code is much easier than to search and select every commands that you can use. Although, it won't be a problem for an experienced user like you. But as I'm new to GDevelop, I'm not that comfortable with it as I'm with Blockly.

With Blockly, you don't have to type much. That's too beginner friendly. It's very extensible. See below screenshot how interactive Blockly can be!

![image](https://user-images.githubusercontent.com/28837746/31298551-48e3e092-ab08-11e7-99d1-8c2e678dc667.png)

**Comment by pavi2410** [comment]
@4ian,

> copy-paste, moving actions or conditions, copying/replacing parameters

These all are supported by Blockly.

> Also it seems that events takes less space on the screen so you can see more thing compared to blocks that takes a lot a space to express simple things.

Blockly also has in-built zoom controls as the blocks are basically rendered with SVG.

> Even for doing simple mathematical operations, using Blockly you have to use the blocks. It's nice to get started, but I highly doubt you can be proficient by doing this... So in the end I'm afraid that it would be more an obstacle for users than a benefit.

But that's a benefit for a beginner, who can create games without reading a lot of docs to know what commands are supported by events system.

> Technically, such a feature would need to implement both support for events and Blockly in GDevelop, to have a compatibility/translations between them and to remake/adapt all the code generation with Blockly. All events, actions, conditions and expressions would need to be converted to blockly - and I'm not even sure how parameters types supported by GDevelop can be handled by Blockly.

Google has a [Codelab tutorial](https://codelabs.developers.google.com/codelabs/blockly-web/#0) on Blockly which would be best if you want to know how Blockly works. It is not tough to implement.

Also [Blockly demo](https://blockly-demo.appspot.com/static/demos/index.html) and [Blockly Games](https://blockly-games.appspot.com/), if you have not seen it, are great place to know some of the possibilities with Blockly.

**Comment by blurymind** [comment]
with blockly you assemble puzzle pieces. It gets as convoluted as real
code- as you need  to know what pieces fit where.

Gdevelop's event sheet is better because it has only two categories- left
and right - condition and action

**Comment by blurymind** [comment]
@4ian please don't scrap the events sheet system - it is gdevelop's strongest feature and now that the editor is becoming much more responsive - the event sheet is a pleasure to use.
@pavi2410 please try to the newIDE - the event sheet works better in it. Try to get used to it before dismissing it for what you have already become accustomed to by putting in the time.
Give it as much time as blockly took to learn
