### ISSUE TITLE
Impossibility of correct translation GD

### ISSUE THREAD

**Issue by ale26reg** [4ian/GD#393]
In english translation are used currently the same lines for condition for sound object and 3D Box object:

#: ../Extensions//Box3DObject/Extension.cpp:213
#: ../Extensions//SoundObject/Extension.cpp:186
msgid "Pitch of _PARAM0_ is _PARAM1__PARAM2_"

In Russian you just can't translate "Pitch" equally in both cases. You must use **Тон** or **Высота тона** for sound and **Тангаж** or **Угол вращения вокруг поперечной оси** for 3D objects rotation. I also can't to translate "Pitch" just as **Высота** in both cases because **Высота** in case of sound means "Pitch" but in case of 3D object it means "Height". I don't know how it is works in other languadges,, but at first sight there are the same situation: Español - **Altura** and **Cabeceo**; German - **Ton** and **Nicken**.

**Comment by Lizard-13** [comment]
Fixed in #394 (if get merged) :)

**Comment by ale26reg** [comment]
Thanks alot!
