### ISSUE TITLE
Something wrong with error message

### ISSUE THREAD

**Issue by ale26reg** [4ian/GD#400]
In English all works prefectly, but in other languages the "errror message" shown incorrectly: instead of a part of the sentence, an abracadabra is displayed.

[Screenshot in English](https://prntscr.com/gx06sd)
[Screenshot in German](http://prntscr.com/gx0jft)
[Screenshot in Spanish](http://prntscr.com/gx0i6l)
[Screenshot in Russian](http://prntscr.com/gx0kwo)

**Comment by 4ian** [comment]
Closing as should be working now
