### ISSUE TITLE
showing different pop up when player will be touch on single blocks

### ISSUE THREAD

**Issue by sagarkodte** [4ian/GD#419]
I want to show some tips when player will be touch brown block. Is it possible?

**Comment by 4ian** [comment]
You should ask this on the forum : http://forum.compilgames.net :)
This GitHub issues page is for discussing about GDevelop development itself. I'm closing the issue then ;)

**Comment by sagarkodte** [comment]
forum is not working. It's automatically logout randomly when clicking on any link.
