### ISSUE TITLE
Sprite Object Editor : Ok/Cancel buttons

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#43]
The sprite object editor doesn't have any of those buttons. It may be useful if you wants to cancel all the changes you've made. Also, it avoids GD to rely on the dialog close button (that's causing troubles on Gnome 3 because modal dialogs are fixed and without close buttons).
If a "Cancel" button is added, it means the editor will have to copy the data before changing it (currently, it directly changes the data on the sprite).

![capture d ecran de 2014-10-14 20 46 31](https://cloud.githubusercontent.com/assets/964512/4634675/7a413e36-53d2-11e4-9b1d-3855b21a525f.png)

**Comment by 4ian** [comment]
I'm closing this as it's now done in GDevelop 5 :)
