### ISSUE TITLE
Persistent of deleted objects

### ISSUE THREAD

**Issue by noz1ng** [4ian/GD#436]
After deleting some of my added objects, they still exists in project json. A sort of garbage. Yes, i deleted them completely, using IDE. Project json just grows bigger, with every added or removed object, storing EVERY ever added resource. It is normal?

**Comment by Lizard-13** [comment]
If you reopen the project, the deleted objects are loaded?

**Comment by 4ian** [comment]
Resources are not properly loaded. I'm going to fix this for the next beta!

**Comment by 4ian** [comment]
I've released beta 24 where you can open the resources editor and remove useless images if you don't need them anymore.
I'll implement an automatic unused resource detection and removal later! :)

I'm closing this issue as I consider that this is fixed 😃
