### ISSUE TITLE
Pixel perfect collision

### ISSUE THREAD

**Issue by noz1ng** [4ian/GD#437]
I know, im totally newbie to things like that, but...

Let assume, that we have created sprite object, and attached to him ACCURATELY cut out image. So, in this case, the image borders should EXACTLY match the sprite object borders. Am i right? If so, pixel perfect collision event SHOULD trigger only that way, as it says. But now, it triggers by colliding outer image borders, according to the raster size, but not the image itself. So, what difference between pixel perfect and simple collision in this case?

**Comment by Lizard-13** [comment]
In HTML5 there is no difference at all, pixel-perfect collision is in the TODO list: [#L63](https://github.com/4ian/GD/blob/648bd1ff2eefd0f4b05b127688df298c33cb3b27/GDJS/GDJS/Extensions/Builtin/SpriteExtension.cpp#L63)
