### ISSUE TITLE
Feature Request: GD5 - Middle mouse button drag scroll camera view

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#442]
Currently you are able to move objects in the scene either by using the left or middle mouse button.
It would be nice if the middle button would be used to drag the camera around instead of selecting / moving objects in the scene.
Using the scroll bars to move the camera view is a little inconvenient.

**Comment by 4ian** [comment]
It's hidden but you can also keep pressing the Space bar and drag'n'drop to move on the scene :)

**Comment by Nnarol** [comment]
Wend1go: I just tried this and it seems to work in both old and new editors, at least under Windows. So I guess this is now solved, right?

**Comment by blurymind** [comment]
Yup, its in. I think we can close this now

**Comment by 4ian** [comment]
Indeed! Closing this now 👍
