### ISSUE TITLE
Pixelart Game

### ISSUE THREAD

**Issue by AGiralli** [4ian/GD#446]
Hi,
I'm trying to make a pixel-art game with GDevelop and I'm using pretty small images.
But whenever I try to import those sprites onto the screen the images get blurred...

Sombody told me, that I should turn of some option in the Image menu, but I only have a Resources menu.

I mean, I could scale the images up, but it would be a hell of a lot of work and it also would make the game much slower using such big images.

Can someone help me please?
Thank you

**Comment by 4ian** [comment]
Are you using GD4 or GD5?
There is an options in GD4 but I've not yet added it to the Resources menu in GD5. Will do that really soon! It's added to my roadmap

**Comment by Lizard-13** [comment]
Please make the option a checkbox instead a "Yes"/"No" random-string box ;)

**Comment by AGiralli** [comment]
I'm currently using GD5.
And I would be very happy to see such a feature sooner or later ^^.
Thx for your fast answer.

**Comment by 4ian** [comment]
You can now select a resource in the Resources editor, and see a checkbox "Smooth the image" that you can uncheck :)

For now it's a bit tedious as you have to do this for every single image in your game :/ But I tried to add this as soon as possible so I'll add multiple selection later!

<img width="800" alt="screenshot 2018-02-25 23 44 59" src="https://user-images.githubusercontent.com/1280130/36647443-15fa4b7e-1a86-11e8-9740-23bec096e1ad.png">

**Comment by AGiralli** [comment]
Thank you very much!

It made making my game difficult and I'm very glad, that you could fix this so fast.
This good communication is yet another thing I really like about this game creator :)

**Comment by 4ian** [comment]
Closing this as it's resolved :)
