### ISSUE TITLE
Feature Request: Include Ace Editor into GD5

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#454]
Ace editor is a code editor written in JavaScript which is designed for being embedded into websites. It has syntax highlighting and code completion for several languages including JavaScript and C++. There is also a react module.
More infos in my forum thread:
http://compilgames.net/forum/viewtopic.php?f=22&t=9719#p65314

EDIT:
Link to forum should work now

**Comment by 4ian** [comment]
That is indeed an idea that I want to implement at some point.  😃 There are a few differents editor that can be used to do this:

* https://github.com/superRaytin/react-monaco-editor (which is the editor powering Visual Studio Code - so quite powerful and working very well)
* https://github.com/securingsincity/react-ace (the one that you mentionned)
* https://github.com/JedWatson/react-codemirror
and probably some others too!

The main things to consider for implementing one of them is:
* How **lightweight** and **performant** the editor is, in particular knowing that more than one editor could be displayed and that users could quickly switch from a code event to another (so we don't want to wait for multiple seconds). One workaround could be to always have an instance of a single editor in memory or hidden and then displayed with the code when needed.
* The size overhead (not a problem for the desktop version, it's more an issue for the loading time of the web app). Code splitting could be helpful, meaning that the code editor would not be downloaded by the web app, unless a code event is opened.
* How well it supports adding completions.
* How easy it is to integrate with React (in my list I've only added react wrappers around the editors so it's a good start).

**Comment by blurymind** [comment]
This would be very very useful if gdevelop had a plugin api that uses javascript- similar to what construct2/3 has.

If that was the case, people who know javascript would be able to create new behaviors and share them with the community :) 

The link to the forum is dead for some reason btw

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/W0mYtxMy/80-include-a-code-editor-into-gdevelop-5

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)

**Comment by 4ian** [comment]
Work in progress here: https://github.com/4ian/GD/pull/586 :)
