### ISSUE TITLE
Flickering PIXI.js

### ISSUE THREAD

**Issue by Bouh** [4ian/GD#463]
Hello

I use my phone Huawei P8 Lite 2016 for test somes games made with GD and the game make flickering and crash, this code bellow fix the problem : 

runtimegame-pixi-renderer.js 
 
`this._pixiRenderer = PIXI.autoDetectRenderer(width=this._game.getDefaultWidth(),  height=this._game.getDefaultHeight(), {transparent: true} );`

[Demo of flickering and crash on Android ](https://streamable.com/55wsm)with [Pick'n Mine](https://play.google.com/store/apps/details?id=pick.n.mine&rdid=pick.n.mine), The game crash too with other exports or other games.

**Comment by Wend1go** [comment]
#566 should fix this

**Comment by 4ian** [comment]
Closing this as the fix is merged and is in the new version :)
@Bouh I totally missed that you had presented here the solution. Please don't hesitate to ping me again if I forget something like this in the future!

**Comment by KinkGD** [comment]
Hello,

I'm facing "almost" the same issue i guess : my apk flicker and crash on a device "[Runbo F1 plus](https://runbo.eu.com/wp-content/uploads/2017/08/Runbo-F1-PLUS-SPECS.pdf)" with Nougat 7.0.

From all the android devices i was able to use for my test (and i tested 6 different devices), it's the only one wich encounter this issue.

Am i the only one ? I've seen @Wend1go writing about this on trello : https://trello.com/c/vMX7TOkv/130-remove-the-beta-from-the-gd5-version-number#comment-5b7efb43e208850ec2b6c2a0
