### ISSUE TITLE
windows version - use zipped binaries instead of setup.exe

### ISSUE THREAD

**Issue by blurymind** [4ian/GD#469]
It would make it much easier to test and deploy new versions of gdevelop if the releases come in zipped binaries instead of setup files. Here is why:

- Sometimes we have no administrator permissions to install software - especially on work and school machines. This immediately cuts off desktop access to gdevelop on any non personal computers.
- Installing a new bleeding edge release requires to uninstall the previous bleeding edge release- which adds extra time and hassle to upgrade
- sometimes we want to have one or more previous versions of the software at hand - especially when looking for regressions. Using simple unzipped folders instead of setup installers makes it more manageable
- Ability to run the software from a flash thumb without extra preparation

Godot engine uses this approach and it's brilliant. The whole engine is on a single executable file that takes a single click to run and has no dependencies. The same thing is for the Love engine - it makes them really easy to show on friend's computers and other public places - very very easy to jump into on gamejam events where maybe some team members dont have the engine and installing it might sound like a hassle to them - especially if they have never tried it. Removing the requirement to do a system install makes it easier to jump into and play with

You could mix the two approaches:
portable version on bleeding edge versions
installers + portable on stable releases

I found I can actually unzip the installer too - but not everyone might figure it out

**Comment by blurymind** [comment]
That is a good idea :) I am personally not a fan of installers and have had to hack around workarounds to get software to run on computers without admin rights. 
Some installers can not be simply unzipped and need more specialized tools to extract their contents, others are like gdevelop's - most people don't seem to know about this.

I doubt they will go to gdevelop's wiki when windows tells them that they dont have admin rights to install the software

**Comment by Nnarol** [comment]
> I found I can actually unzip the installer too - but not everyone might figure it out

> Could add this line under the windows download page maybe:
> Alternatively you can extract setup.exe with 7zip and run gdevelop without installing it

If the two are equivalent, I think it is better to just provide a separate download link to a renamed installer with a .zip/.7z/whatever extension.
Compared to documenting separately that the .exe can be extracted with specifically 7zip or another program, to me this seems:

 - More noticeable: There is a download option, no way to miss it if you want to download the program.
 - More maintainable: Will the maintainer remember to update the documentation if the format of the .exe variant changes in the future for whatever reason? Sure, people will complain and it won't go unnoticed, but still.
 - More straightforward: It is common practice to provide an archive and an installer separately.

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/DkOvbuXZ/79-distribute-gdevelop-5-in-zipped-binaries-on-windows-in-addition-to-executable

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)
