### ISSUE TITLE
Use wxWidgets 3.0.2 (under Linux)

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#47]
The second minor version of wxWidgets 3.0 has been released. It brings some bug fixes, so it's highly recommended to use it now for GDevelop.
It doesn't cause any problems to GDevelop as this version is fully compatible with the older one.

(We should still consider using this version under Windows, PR #3 is not mergeable anymore, but we can make another one just to switch wx version, without changing mingw)

**Comment by 4ian** [comment]
I close the issue now that GD was updated to use system provided wxWidgets on Linux (3.0.x, often 3.0.2) and the precompiled version of wxWidgets on Windows is also the 3.0.2 that you compiled :)
