### ISSUE TITLE
Import GD4 Project into GD5

### ISSUE THREAD

**Issue by Translator5** [4ian/GD#471]
Is there any way to migrate the old Project to the new GD-Version?
Maybe you would like to create this as a new feature?

For my case it is not that tragic to have it, but It would save some extra moves.

Edit: ... yeah - this is the situation that arises when you change you engine version during the development :laughing:

**Comment by 4ian** [comment]
http://wiki.compilgames.net/doku.php/gdevelop5/getting_started/open-gdevelop-4-project 😉 

Make sure to keep a copy of the GD4 project
