### ISSUE TITLE
newIde event sheet- smarter object search - show only objects that do have the behavior

### ISSUE THREAD

**Issue by blurymind** [4ian/GD#473]
When selecting an object to check in the event sheet, gdevelop lets you select any object- even objects that dont contain the relevant behavior check. This makes it harder to find the ones that do have it.

My suggestion is to have the search automatically filter out only relevant results,instead of showing this red warning whenever for example the object you selected in the list doesnt have the behavior attached to it:
![eventsheetbehaviorobjectsearch](https://user-images.githubusercontent.com/6495061/38957422-7c65a242-4352-11e8-9091-2e89aaffec7b.PNG)

see how many there are:
![untitled](https://user-images.githubusercontent.com/6495061/38957794-6416c8d2-4353-11e8-89d1-09494dff5ea8.png)

It would be way more intuitive to the user if the newIde automatically showed only objects that have the platformer behavior that contains the isonfloor check

**Comment by 4ian** [comment]
That would be the best indeed :) But what is difficult here is that the object and the behavior are two different fields of the action/condition, and in particular the object field is not aware of the existence of the other field, which make it difficult to know that filtering should happen.

To do this, there should be some kind of filtering that would re-group objects + behaviors into a single field that could have all information to do the filtering of objects :)
Quite possible to do this in a clean way but need a bit of work.

**Comment by blurymind** [comment]
I tried digging around the code and couldn't figure out how to make it filter only relevant results in a clean way. It would make a world of difference if it does :)

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/lG9A9leO/78-show-only-objects-that-do-have-the-behavior-when-selecting-an-object

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)
