### ISSUE TITLE
[Beta 30 - Windows 10] Moving events

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GD#475]
Hi, the way to move events in Gd5 look really good.
But it has some limits, I don't know if it's because I have too many events or if it's because I have groups, but if Im trying to move an event, it mess the whole view of the events.
Here is a gif to show you I think you would surely understand:
![bug gdevelop](https://user-images.githubusercontent.com/19387127/39077060-714cfb86-44ff-11e8-8c36-e2daa423acb4.gif)

**Comment by 4ian** [comment]
Transition should not be perfect but still not mess like this. Which system are you using GD on?

**Comment by Jeje2201** [comment]
As stated in the title of the issue, Windows 10

**Comment by blurymind** [comment]
@Jeje2201  what web browser? Or is thus the desktop app?

It might help sharing the messed up file

**Comment by Jeje2201** [comment]
@Blurymind that's from the Desktop app
I don't use the browser one since we can't open a project from here

**Comment by blurymind** [comment]
@Jeje2201 can you share the scene that causes this? What steps could be followed to reproduce the error? Does it consistently happen

**Comment by Jeje2201** [comment]
Just letting you know it still happen with the last beta (33), this gif is from this one as you can see with the debugger icon

> can you share the scene that causes this?

Sure thing, I removed all scene of my project and created a new one, here is a link for the .json project
[game.zip](https://github.com/4ian/GD/files/1952538/game.zip)

> What steps could be followed to reproduce the error? 

Just moving an event in a close group event, here is the example with the json I gave you. Im taking the top event, moving it into close event, you can see the bug view happening, and then I open them showing you what's in, but you have the json file to have fun with it too 😜 
And here is a gif to show you an example of steps. If im doing the same steps but letting the groups open before moving it, this bug does not happen, the view isn't perfect, but still, not that buggy
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19387127/39325629-fa3f4998-4992-11e8-8a35-59881ca563de.gif)

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: 
https://trello.com/c/pORAQz7y/77-improve-dragndrop-of-events

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)
