### ISSUE TITLE
Save informations in spreadsheet

### ISSUE THREAD

**Issue by PabDom** [4ian/GD#476]
Hi all !

I work in a french association, where an adhesion is obligatory at the entry. It's just about write first and last name, mail adresse and zipcode.
We found a computer to make those adhesions informatically, and I'd like to do some soft with GDevelop to make it aesthetically.
Is there a way to make GDevelop save data into a Excel spreadsheet instead of a txt file ? It would make this easier to consult those files in a legal way.

Thx for the answer !

Pablo

**Comment by 4ian** [comment]
I think it would be better suited to ask for this question in the forum. 
Issues in GitHub are more like for technical issues or development related discussions.

Can you post your message on the forum and/or discord? Other members will help you there.
I'm not sure that it's really feasible for now to write in an Excel file.. Maybe you can try to write .csv file?
