### ISSUE TITLE
Footer of text object go outside of the screen if too much texts.

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GD#480]
If you're typing text in a text object but you have lots of stuff to type in, like a dialogue or something else, the footer of text object where Cancel and Apply button are, follow the size of the text edition and so go out of the screen.
For now the way to bypass this is to go to behaviors and so you can press apply
And here is a gif as always to show what im talking about:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19387127/39257010-b0c355bc-48b0-11e8-9139-e4a6b6513490.gif)
( I know for the text Im doing in the exemple I can just create a loop 50 times, do +1 of a variable and then apply it to a text, blablabla 😄 But Im just talking about the fact it can be annoying for long text )

**Comment by 4ian** [comment]
Good catch, thanks for reporting it :) Fixed for next version! 👍
