### ISSUE TITLE
Can't toggle developer tools anymore in scene preview

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GD#482]
With Gd31 update, we can't toggle the developer tool anymore when we start a preview of a scene.
As stated [here](https://twitter.com/Game_Develop/status/989446607497256960) on Twitter
>  It should not be the case, I guess it is because the menu was removed.

I found out we can still enable it from the IDE while waiting for it to be back in game preview, it update when we interact in the scene preview too, so it's not like "PLEASE FIX IT" since we can still reach the developer tools from somewhere else.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/19387127/39300881-7a5b2426-494d-11e8-8f8f-312500881a7d.gif)

**Comment by 4ian** [comment]
Menu should be back in beta 33 :)
