### ISSUE TITLE
Time scale layer feature

### ISSUE THREAD

**Issue by KinkGD** [4ian/GD#489]
Gdevelop 4.0.97
Native platform
Time scale per layer feature in compiled executable trouble.

![image](https://user-images.githubusercontent.com/8144048/39550073-57bad2d2-4e60-11e8-998e-43101e5bdc44.png)

In preview, the default option to use base layer instead of specific one in this action works great. As illustrated on my picture, missing "" in the action. if i compile executable : the action (and whole event) just don't work.

I think it's just the missing "" by default, because if i check the box to pick up a layer, then select the base layer, it adds "", and the event works fine both in preview and compiled game.

**Comment by 4ian** [comment]
Strange, as it's working the same way as for example the action to change the zoom of the camera.
Could you try in a test game the same thing but with the camera zoom action?

**Comment by KinkGD** [comment]
well.. don't know why... i can't reproduce it on a new project. With camera zoom,it's working too.. No problem !

This should be linked to my game... Something else might pertub it.

i suppose you can close the issue, but both timescale per layer and camera zoom are not working in my game withtout "" for base layer.. really strange.
