### ISSUE TITLE
Native compilation open a 2nd explorer.exe process when opening the export folder at the end of compilation

### ISSUE THREAD

**Issue by KinkGD** [4ian/GD#490]
As the title said !

Gdevelop 4.0.97
Native platform
related with end of a compilation.
OS : Windows 10

[(http://oi65.tinypic.com/vi0huo.jpg)]

When the compilation is ended, user is invited to open the export folder : if you click yes, it opens a second explorer.exe. The issue is that until this process isn't killed, you can't access Gdevelop IDE anymore.

Minor problem, but not really confortable.

**Comment by 4ian** [comment]
Ok... let's close this then! Maybe something on your project is triggering this behavior but I can't see how the content of a game would change the way explorer is opened.
