### ISSUE TITLE
[Repository Suggestion] Implement more and specific development labels

### ISSUE THREAD

**Issue by Jose-Moreno** [4ian/GD#498]
Hi, I've been looking into the repo and I think it would be great if you could enable a few labels to sort out the issues since currently it's a bit difficult to see which bugs are a priority and which aren't. Also I think it's important that other interested contributors can know at a glance which tasks are meant for "veteran" developers and which for "new" or "junior" developers in order to help.

A simple proposal for labels would be to have:

**Bug Report labels**

- [ ] Bug: Logic
- [ ] Bug: Warning
- [ ] Bug: Critical
- [ ] Bug: Crash

**Architecture related labels**

- [ ] Core
- [ ] GDCpp
- [ ] GDJS
- [ ] IDE
- [ ] newIDE
- [ ] Extensions / Plugins

**OS labels** 
To sort development environment specific reports

- [x] Win
- [x] Mac
- [x] Linux
- [ ] Web Editor

**Platform Deployment labels**

- [ ] HTML5
- [ ] WEBGL
- [ ] IOS
- [ ] ANDROID
- [ ] Native
- [ ] UWP

**Developer expertise category labels**

- [ ] Junior
- [ ] Seasoned
- [ ] Veteran

**User interaction labels**

- [ ] Usability (US)
- [ ] Feature Request (FR)
- [x] enhancement / Feature Improvement (FI)
- [ ] Pull Request (PR)
- [ ] Feature Discussion (FD)

What do you think? Hopefully this will help others to sort their contribution efforts in a more structured way, also if anyone else has more ideas for labels please add your own suggestions as well.

**Comment by Jose-Moreno** [comment]
I noticed there are some labels implemented so I marked those that already exist, while there are others that are more focused which I didn't consider. I suppose this request is still valid, but now I see that maybe the small amount of contributors might not need them to make this system as efficient as I thought it would be. Nevertheless here's hoping more people would come to assist the project I think it'd be a good way to welcome them :smiley:

**Comment by 4ian** [comment]
Hey! Thanks for the suggestion :)

For now the number of contributor makes that we don't need tons of labels but I think I can still add some to distinguish between GD4 and GD5, and mark some issues as "Good first issue" for new contributors :)

**Comment by 4ian** [comment]
I'm closing this as I've flagged most issues with labels. :)
In particular, there is a "Good first issue" to help new contributors to get started with the codebase!

**Comment by Jose-Moreno** [comment]
@4ian Alright! thanks for taking a look and considering it anyway :slightly_smiling_face:
