### ISSUE TITLE
Move window mask button in Grid menu [$5]

### ISSUE THREAD

**Issue by 4ian** [4ian/GD#502]
## Description
The window mask button is an icon on the toolbar to enable/disable displaying a rectangle on the scene editor that represents the size of the window.
This button is a feature that is useful but maybe not worth showing a button only for it in the toolbar (it's taking space)

## Solution suggested
As the mask is something that is helping to align and place objects like the grid, we could move it to an extra option in the menu displayed when clicking on the Grid button in the toolbar.

## Alternatives considered
We can let the button where it is now but I think it's taking a lot of space compared to the number of times it's used. Having an extra click to do is ok for this feature.

**Comment by saurvs** [comment]
I'd like to work on this.

**Comment by saurvs** [comment]
@4ian should this be done for the old or new editor, or both?

**Comment by 4ian** [comment]
New editor :)

**Comment by Bouh** [comment]
I think i have completed this bounty.
If I can put the reward back on the line, I'd like to. 
For a next issue :)

**Comment by 4ian** [comment]
Thanks! That's nice of you. It's the first time I use Bountysource so we'll see how it works once we close the issue 👍

**Comment by 4ian** [comment]
Closing this issue as it's merged. Thanks!
