### ISSUE TITLE
The preview start from the first scene and not the one we are in

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GD#505]
## Describe the bug
When we are in a scene and start the preview, it doesn't start the preview of the scene we were in (like the previous versions) but it start from the first scene in the scene list.

## To Reproduce
1. Have 2 scenes
2. Go to the second scene
3. Start the preview
4. The preview would start the first scene

## Other details
* Windows 10, Gd5 Beta 39

**Comment by 4ian** [comment]
Thanks for the well redacted bug report! 😃
I indeed broke it 😭That's fixed in v40!

**Comment by Jeje2201** [comment]
Haha thanks 😄
