### ISSUE TITLE
Copy/Cut & Paste doesn't work on empty target event

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#508]
**Issue:**
In GD5 Beta 39 it is not possible to copy/cut & paste conditions or actions into an empty event.

**Steps to reproduce:**
Add an event and create an action (or condition)
Copy or cut the action
Add a second event
Paste the action -> nothing happens

**Comment by Jeje2201** [comment]
It's just not implement yet, updates are comming days after days implementing more and more features, we just have to wait.
For now you have to create an event first before copy others, we are all confront to this, just create a blank event, past the event you did copy, and delete the blank event.

**Comment by 4ian** [comment]
Can you do a small gif/video to make sure about what we're talking about there?

**Comment by Jeje2201** [comment]
Im guessing he meant you can't copy a condition/action and past it in an empty one like that. Because this was possible in Gd4.
![image](https://user-images.githubusercontent.com/19387127/40742642-7205644a-644f-11e8-8a46-ad1705487e89.png)

**Comment by Wend1go** [comment]
Yes exactly as @Jeje2201 stated.

(I know it isn't implemented yet. This issue is just a reminder. ;) )

**Comment by Wend1go** [comment]
Just checked, using the context menu exactly on the add condition/action link indeed works.
I always try to paste to the event itself.
Opening the context menu by right clicking on the event itself and choosing paste doesn't do anything.
Maybe the selected event itself could listen for CTRG+V and add the copied action/condition. Since a click on the add action/condition link immediately opens the action/condition editor, the keyboard short cuts don't work here.

**Comment by Jeje2201** [comment]
It's working for me, Gd5 Beta40 Windows 10

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19387127/40777335-e14fdfc8-64cd-11e8-8227-0eaf5491ed1a.gif)

**Comment by Jeje2201** [comment]
That's what I was asking here 2months ago -> https://twitter.com/Mr_Jeje_/status/982985992079634434
😭

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/bL8DdEe6/84-enable-to-focus-empty-conditions-actions-list-and-use-shortcut-to-paste-condition-action

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)
