### ISSUE TITLE
GD5 dark theme has very low contrast in instances list

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#509]
The instances list has a very low contrast in the dark theme which makes it very hard to read:
![image](https://user-images.githubusercontent.com/7413059/40838828-19184260-65a0-11e8-8be2-058f82f29ee9.png)

**Comment by 4ian** [comment]
Indeed. The background color are hardcoded and would need to be read from the theme colors instead.

**Comment by 4ian** [comment]
Fixed in https://github.com/4ian/GD/commit/ad9abd971c84b29fbeb4173d64dafcfe676280b8 :)

![image](https://user-images.githubusercontent.com/1280130/41681806-a5dc01e6-74cd-11e8-81f3-f5c633f71f82.png)
