### ISSUE TITLE
Looping the ogg

### ISSUE THREAD

**Issue by CuddleFox** [4ian/GD#510]
That's 5 versions of GDevelop coming out and nobody thought to make the software detect LOOPSTART and LOOPLENGTH to be able to loop an ogg? Or have you already tried and it's not possible? :o

**Comment by 4ian** [comment]
Hey,

Next time, can you follow the template of the issue that I've created? Sounds should be looping properly.
If that's not the case, please create a sample game showing the issue and uploading it. GDevelop is a massive software and there is lots of things to do on it.

Thanks! :)

**Comment by 4ian** [comment]
I'm closing this as we don't have more details! Feel free to re-open if you have more details and an example.
