### ISSUE TITLE
Animations not working properly in the preview of project  (windows 10)

### ISSUE THREAD

**Issue by Rodox84** [4ian/GD#515]
My player do the idle animation and nothing more, i configure for change the animation but  he stop in the first animation configured  (windows 10)

**Comment by 4ian** [comment]
Hi, 
This is unlikely to be an issue with GDevelop. For now, unless you have a rock solid sample game as a proof that something is going wrong, please use the forum or the Discord chat to get help from the community on your game :)

Thanks!

**Comment by Lizard-13** [comment]
Just to note that surely it has to do with other events switching another animation in the same frame, anyway go to the forum if you want more info ;)
