### ISSUE TITLE
Animations events doesn´t work

### ISSUE THREAD

**Issue by Rodox84** [4ian/GD#516]
The animations event´s play in the test only the first animation, configurated, omiting the rest of the others
(Windows 10)

**Comment by Lizard-13** [comment]
Do you have an example to test it?, as before, surely another event is switching to other animation(s) in the same frame.

**Comment by 4ian** [comment]
@Rodox84 could you please ask these kind of questions on the forum or the Discord please?
I already asked you about this on the other issue :/ Not cool.

**Comment by 4ian** [comment]
Thanks! :)
