### ISSUE TITLE
Installing GDevelop

### ISSUE THREAD

**Issue by VulpineVortex67** [4ian/GD#525]
Hello, I installed GDevelop and I keep getting errors with compiling and running my games, usually reating to missing dlls and C++ runtime library crashes. I have tried reinstalling but nothing works. Is there any programs I need to install before using GDevelop (i.e. Microsoft Studio Redistribute 2015)? I can't get any games working, they always give me this error:

Microsoft Visual C++ Runtime Library

This application has requested the Runtime to terminate it in an unusual way.

I really want to use GDevelop, but this keeps happening. Is there something I forgot to install alongside GDevelop 4?

**Comment by 4ian** [comment]
Is there any particular reason for you to use GDevelop 4? I would highly recommend to use GDevelop 5, which has better support and is improving quickly :)

**Comment by 4ian** [comment]
Oh I see you're already opened https://github.com/4ian/GD/issues/523
Please only open one issue, otherwise this confuses a lot and make harder to see what's happening. I'm closing this one!

**Comment by VulpineVortex67** [comment]
Sorry about that, I was so confused myself with many different problems. I understand. Also, I noticed the latest update of GDevelop 5 had windows export support, which is what I needed. So, I switched to my 64-bit laptop. I was only using GDevelop 4 because I hadn't noticed the GDevelop 5 update yet. It is all good now


________________________________
