### ISSUE TITLE
newIde - ability to set action points/ mask points by clicking on the preview instead of typing x/y

### ISSUE THREAD

**Issue by blurymind** [4ian/GD#532]
## Description
Setting action points or colision mask points in the new ide is a bit cumbersome  in the newide at the moment. You can't just click with your mouse on the location where you want to plant a point. Instead you can only enter numeric values

## Solution suggested
A more intuitive option to have is to:

Be able to select a point row in the pointeditor - to be active and then click with the mouse in the point preview window to set the location of the point (radio or checkbox button?)
Keep the numerical input - but also allow to simply click to set location - as it is a quicker/more intuitive way to do it 

I was actually wondering wether to try to add this, but wasn't sure if it is already planned by @4ian and he has a specific design in mind, but that design requires something else to be implemented first

**Comment by 4ian** [comment]
It's indeed a bit cumbersome right now.

I'd like to have this but haven't plan anything in the short term. Any improvement is welcome :)

I guess the simplest design would be that, when a text field is focused for X or Y coordinate, then clicking on the preview will move the point at the mouse position.
Another similar way to do it is to use checkboxes to be able to select a point - may make the fact that the point is selected and that an action is possible (clicking to move the point) more clear and discoverable.

For both solutions I think we still need a small explanation text (`<EmptyMessage>` component) to tell that points can be moved by selecting them and clicking on the preview.

**Comment by blurymind** [comment]
@4ian that is a good idea! Instead of adding a checkbox or radio button - just be able to click and drag the actual points to the location would be more ellegant

I might give this a try after getting thenew piskel stuff ready :)

**Comment by 4ian** [comment]
Click drag may be the more obvious to anyone, but not sure if it's really easy to do.
Moving multiple points to do seem like a really useful use case. I even think that it will confuse users and make people move multiple points without noticing and frustrate most users doing this mistake. So let's keep a single point with a radiobox if you go this way :)

**Comment by zatsme** [comment]
Most guis I've used seem to allow to set points by clicking and then
joining the points in a clockwise direction.  To move a point you click and
drag and to add a new point you click space.

To make it easy, why not have an add, modify and clear check boxes?  You
would also be able to reorder points by dragging the numbers up or down the
list.

Zat..

**Comment by Oneil974** [comment]
GD4 drag and drop was working well and in a very simple way, so I think it would be good to have a similar tool.
But for me a problem is persisting with big pictures for scroll over during editing. And now in GD5 big pictures generate a bug and picture is completly outside of canvas limit.
Collision mask is no more at the right position.

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/TUhmcpaA/73-add-ability-to-set-action-points-mask-points-by-clicking-on-the-preview-instead-of-typing-x-y

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)

**Comment by 4ian** [comment]
I've worked on this and this will be available in the next version: https://github.com/4ian/GD/issues/616#issuecomment-418898018

**Comment by blurymind** [comment]
Thank you @4ian !! :)

**Comment by zatsme** [comment]
Can't wait to try it out 😁
