### ISSUE TITLE
Bug with hitbox, for high resolution pictures

### ISSUE THREAD

**Issue by Oneil974** [4ian/GD#534]
Hi, I'm getting problem with GD5 hitbox editing.

I use large picture, and first, it's difficult for scroll over during editing (Maybe my screen resolution 1366x768). Large picture generate a bug and picture is completly outside of canvas limit.
Collision mask is no more at the right position.

What's the max resolution for sprites?

**Comment by 4ian** [comment]
Hey! Can you post a zipped game to help to reproduce the issue?

**Comment by Oneil974** [comment]
![capture d ecran 63](https://user-images.githubusercontent.com/11059074/41736735-671ed4c0-759e-11e8-9410-6bee7f8d111c.png)
![capture d ecran 62](https://user-images.githubusercontent.com/11059074/41736737-6762b58c-759e-11e8-8b19-f2572ff92349.png)
[fond-iso_map_2.zip](https://github.com/4ian/GD/files/2124781/fond-iso_map_2.zip)

**Comment by Oneil974** [comment]
With just the zipped background you could easily reproduce the bug.
Screenshots show you the limits of the background and canvas

**Comment by Oneil974** [comment]
Solution is to use smaller pictures

**Comment by Lizard-13** [comment]
I can confirm there is an offset in the bounding rectangle and collision masks draws
