### ISSUE TITLE
Port newIde to android/ios (mobile)

### ISSUE THREAD

**Issue by blurymind** [4ian/GD#539]
## Description
It would be fantastic if we can get the editor to run with file saving and piskel support  on android- as an apk app!
Since there are not many other alternatives on android- there is a great opportunity to attract more users- as having an engine such as gdevelop on the app store will greatly increase its exposure.

I was wondering how feasible it is- as the newIde built on top of html5, but the web app has no support for file loading and saving. Can we get it on the same level as the electron app?
With ipads now having a stylus and many android tablets too- if we get it to run with piskel on mobile would be incredible- turning gdevelop into a full fledged game creation suite

Construct3 for example can already do that
https://www.construct.net/gb/blogs/construct-official-blog-1/construct-3-on-mobile-866
But their licensing is awful and they are not open source at all

## Solution suggested
One suggestion is to use the same technology that it is currently using to export android games - I am assuming that is cordova

I have both an ipad (ios) and a samsung galaxy tab tablet (android)- So I can help with testing and bug fixing - especially any usability issues related to the touch interface

## Alternatives considered
There are of course other ways to package it into an apk. Not sure if we can just use react-native
https://facebook.github.io/react-native/docs/getting-started.html

Is that something that has ever been planned and is it possible to do?

**Comment by 4ian** [comment]
Short answer is yes that's possible and that's on the road map but probably more in the long term.

One possible caveat is performance, but for what I've tested the web-app is already running quite well on Android (according to the device of course).

> but the web app has no support for file loading and saving. 

This is something that could be added with a bit of rework (in particular with integration with Dropbox, Google Drive, etc...). Something again on the roadmap but more for long term.

> One suggestion is to use the same technology that it is currently using to export android games - I am assuming that is cordova

Cordova is one solution indeed. I'm still not sure if it's even needed now as PWA are becoming mainstream and people will become used to richer application directly in their browser.

> There are of course other ways to package it into an apk. Not sure if we can just use react-native
https://facebook.github.io/react-native/docs/getting-started.html

React Native is a great technology for mobile applications, and superior for most usages compared to Cordova. For GDevelop it's a bit different as the web-app is a complex piece of software relying on both React for rendering the UI, but also Pixi.js. React Native has support for web view so this could be a solution. Material UI is used for all the interface but we would need to abstract all of their component to use React Native one instead - not sure if it's viable.
A solution with React Native would undoubtedly be superior in terms of integration to the platform and the native feeling. On the other hand it would require a major upgrade/rewrite of some components.
I love React Native but not sure it can be used here for now - or not sure we have enough demand to justify dedicating too much time to this.

I think the best way would be to start from the current web-app and:
* Ensure that touch events are properly handled in the scene editor (would also benefit the desktop app for touchscreen like the Microsoft Surface maybe)
* Fix any potential issue on smaller screens (would also benefit the desktop app)
* Add support for saving/loading into a Google Drive/Dropbox (could also be supported on the desktop app!)
* Spot any potential performance issue (would also benefit the desktop app)
* Enjoy :)

**Comment by blurymind** [comment]
@4ian you are right. We are missing some key elements in the web app before this is really doable 👍 
Thank you for taking the time to share your thoughts on this

**Comment by nalcwap** [comment]
good know is possible make for android will be great,thanks

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/DBL5Ffmk/71-add-option-to-embed-itchio-steam-etc-on-forum

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)
