### ISSUE TITLE
GD5: Stuck in camera panning

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#541]
## Describe the bug
Occasionally after selecting an object in the scene and moving it with the mouse the IDE seems to enter and get stuck in "camera panning mode".
When this happens it isn't possible to select objects anymore and moving the mouse with pressed left button moves the camera instead of the selected object.

## To Reproduce
I haven't yet found out what triggers this. It only happens occasionally.

## Workaround
None.
Need to restart the IDE.

**Comment by blurymind** [comment]
Are you middle clicking when moving the object? :)

**Comment by Wend1go** [comment]
I have tried moving an object around while middle mouse panning the camera for a couple of minutes but couldn't trigger the bug.
When trying to scroll via middle mouse button the selected object gets deselected so I usually move the object a bit, pan the camera via middle mouse, move the object again ... until I reach the destination.
So I don't think that I'm using the middle mouse button while moving the object when it occurs.

**Comment by blurymind** [comment]
Something is causing it to get stuck, but we need to figure out what.
Can you try to cause it to happen again and write down the steps to recreate the bug? :)
Its very strange that object selection is triggering viewport panning

**Comment by Wend1go** [comment]
I'll try to keep an eye on the conditions when it occurs the next time.
Is there some place that would be suitable for placing a break point in the code?

**Comment by blurymind** [comment]
from what I remember, this is the function in charge of panning
:)
https://github.com/4ian/GD/blob/master/newIDE/app/src/InstancesEditor/index.js#L337

**Comment by Wend1go** [comment]
> Is it possible that your spacebar key got stuck?

I don't think so, haven't had any problems with it elsewhere.
Will report back when I find out something more.

**Comment by Wend1go** [comment]
It happened again while selecting an object via left mouse button.

```
  shouldMoveView() {
    return this.spacePressed || this.mouseMidButtonPressed;
  }
```
While the bug is active these variables are set:
spacePressed = false
mouseMidButtonPressed = true

mouseMidButtonPressed is true even though I am pressing the left mouse button.
It gets set to false again when I release the left button and is set to true again when I hit the left button again.

**Comment by 4ian** [comment]
There may be an issue with listening for button pressed/de-pressed while the mouse is going outside of the scene editor view.

**Comment by blurymind** [comment]
I will try to fix this when i get back home

**Comment by blurymind** [comment]
@4ian I tried this and I can't seem to trigger it. I tried middle clicking inside after selecting and dragging outside of the window- gdevelop stops panning when leaving.
I tried mid clicking outside the window- nothing happens.

I can add a new mouseleave event listener just in case if you want to?

**Comment by Wend1go** [comment]
`    if (!isMacLike() && evt.button === MID_MOUSE_BUTTON) {
      this.mouseMidButtonPressed = true;
    }
`
isMacLike = false
evt.button is = 0
MID_MOUSE_BUTTON = 1

Even though the values are not equal this.mouseMidButtonPressed is set to true.

**Comment by blurymind** [comment]
very strange. What can be setting `this.mouseMidButtonPressed` to true?
Are you sure that it is true,when evt.button is 0?

One thing I can do is add some code to set it to false if any other mouse button is pressed

**Comment by Wend1go** [comment]
Did someone try GD5 on a MAC lately?
The question is how javascript treats the "false" value from isMacLike, since it is neither 0 nor 1.
Maybe it gets interpreted as a positive value which gets negated by "!" and in combination with the right expression results in a true value.

**Comment by 4ian** [comment]
I develop GDevelop 5 on macOS but `false` is always interpreted as false in Javascript - no trap there. 
`isMacLike()` will always be false on Windows/Linux and `! isMacLike()` will always be true on Windows/Linux.

**Comment by blurymind** [comment]
@Wend1go  What OS and version were you on?
I tried to trigger this on 2 windows 10 x64 computers and one windows 7 x64 computer - using the generic platformer example project

**Comment by Wend1go** [comment]
I'm using Linux Mint 64Bit (haven't tried GD5 on Windows yet)
The bug happens in the official Linux electron version (Beta 42)
I wasn't able to try your suggestion yet. It usually takes more than an hour to trigger the bug.
Will see if I can find more time for testing tomorrow.

**Comment by blurymind** [comment]
@Wend1go do you use mid click to pan or spacebar?

**Comment by Wend1go** [comment]
I always use mid click.

**Comment by Wend1go** [comment]
#546 seams to fix this, thanks @blurymind for your code snippet.
