### ISSUE TITLE
GD5: Add the option to set an object name in the add new object dialog

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#542]
The current way of creating new objects is a little cumbersome since they are all automatically named "NewObject" and the "Edit object" dialogue immediately shows up before one can give it a proper name.
Having to right click on the object, choose Rename and overwrite the old name disturbs the work flow a bit.

It would be nice to have an input box (mandatory) for the object name directly inside either the "add a new object" dialogue or the "Edit object" dialogue that gets opened right after creating the object.
That way one wouldn't have to rename every single object after creation and it would also benefit the piskel editor because a proper object name for the image folder would already be available when it gets launched.

**Comment by blurymind** [comment]
@Wend1go I found this with my personal electron project - electron doesnt actually support having a prompt with text entry - unlike web browsers. There are workarounds of course, but they are not great.

We need to create a new prompt gui class to make this happen.. or use an npm package- which is not great. 
https://www.npmjs.com/package/electron-prompt

I wonder how to best address this

**Comment by blurymind** [comment]
@4ian one thing that would be nice and will help here is have the object list (on the right) automatically select the object that is selected in the editor and even scroll to it. 
If it scrolls to it and even has the name input steal focus on newly created objects- that would even be better

I was actually wondering whether to give this a try  :)

**Comment by Wend1go** [comment]
I wasn't actually talking about a prompt but a mere text box instead. Something like this (just more pretty ;)) 
https://imgur.com/11SCbh3
But @blurymind ' s idea sounds good too, it would be the same approach as in GD4.

**Comment by blurymind** [comment]
@Wend1go  @4ian  How about doing it like this:
![objectnameinput](https://user-images.githubusercontent.com/6495061/42109270-fae0e7ac-7bd4-11e8-8dbb-2ebd3d96f169.gif)
:)
I found this to be the most natural way to do it. It also adreses the fact that the object 
editor is not showing the name of the object being edited

**Comment by Wend1go** [comment]
I like it

**Comment by blurymind** [comment]
@Wend1gomy suggestion is to put it in objectEditorDialog.js instead
I noticed that you are already working on this. Would you be interested in tackling it in your pull request here:
https://github.com/4ian/GD/pull/545
I can give it a try again later this week too if you want :)

**Comment by Wend1go** [comment]
I won't have time to work on GD next weekend, if you have more time give it a try.
Otherwise I could look into it the weekend after next.

**Comment by blurymind** [comment]
Thanks to @4ian 's excellent guidance I made some progress with this and learned some new cool reactjs things. Now an object can also be renamed like this:
![renameobject](https://user-images.githubusercontent.com/6495061/42248211-57e27b56-7f1c-11e8-95f4-050313a74e74.gif)

This might require some bold refactoring of the rename object function - which is right now scattered in two places. My solution works right now - but it doesnt do the check. Moving the check out of the list and into the index would solve it

**Comment by 4ian** [comment]
Yes you probably need to unify the rename function into a single one in the `SceneEditor/index.js` and then pass it down to use it at any point where you need it :)

**Comment by blurymind** [comment]
@4ian I was thinking to keep them separate, because I want the unique name check to happen when the input loses focus and the actual renaming when the user clicks on "apply".
When moving out the check function - make it a simple checkIfObjectNameCanBeUsed(newName) function that returns true or false 

Not sure if thats the best approach, but I think it will make the code easier to understand

**Comment by 4ian** [comment]
Then in this case it makes sense to have a slightly different implementation, but factor common code into a tool function so that the code is easier to read and obvious to implement :)

**Comment by blurymind** [comment]
I will try not to break things or change them too much. Right now its a choice between some refactoring or code replication. :) 
I trust your judgement in this,so will take whatever approach seems most sensible

**Comment by 4ian** [comment]
Having it here looks correct. Could maybe have a label "Object name:" before the text field and ensure the text field takes the whole width of the dialog.

**Comment by blurymind** [comment]
Made a pull here
https://github.com/4ian/GD/pull/547

**Comment by 4ian** [comment]
Great job in implementing this :) I think we can now close this :)

**Comment by Wend1go** [comment]
Thanks a lot :)

**Comment by magicvince** [comment]
There's a bug in this option: If I type unfortunately a space in the name, my GD freeze all my computer and I have to reboot it. It seems to be a bug. I'm using GD 5.00 beta 62 with Linux Debian (stretch) Mint
