### ISSUE TITLE
Error when Exporting to Online Service

### ISSUE THREAD

**Issue by VulpineVortex67** [4ian/GD#551]
Hello, I recently have had problems exporting my game to the online compiling service for GDevelop with the following error:

Error: EROFS: read-only file system, mkdir '/worker/app-8012470b-79c4-4be3-98c3-c707720ff5cc'

Is there a way to fix this on my end, or is it something on the service's end. It used to work before, I can't export my game to Windows without this. Does anyone know what is going on?

**Comment by VulpineVortex67** [comment]
I tried the changing the folder permissions, my user already had full access, so I guess it is something on the server side. Is there any way to tell when the service will be back up?

**Comment by VulpineVortex67** [comment]
Until the service is back online. Could anyone tell me  how to manually compile my game for windows

**Comment by 4ian** [comment]
Thanks for reporting it and sorry for the disruption! The worker doing the compilation of games should be back to normal and everything should work smoothly now :)
I have identified what was the error and will make sure that it's not happening again!

**Comment by VulpineVortex67** [comment]
Thank you. Have a nice day. :)

**Comment by Lizard-13** [comment]
@4ian The workers seems to be down again, same error message

**Comment by 4ian** [comment]
Should be back up an running. Workers were too tight on disk space, increased it so hopefully won't get any problem from this side.

**Comment by 4ian** [comment]
@Lizard-13 Thanks for letting me now :)
