### ISSUE TITLE
[Feature Request] Forum: Add option to embed itch.io, Steam, etc.

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#553]
It would be nice if it was possible to embed iframes to sites like itch.io or Steam in the game showcase area of the forum.
If I remember correctly the forum is based on phpbb. According to the link below it is possible to add custom bbcode tags there. 
For example:
 `<iframe src="https://itch.io/embed/{yourgameidhere}" width="552" height="167" frameborder="0"></iframe>`) 

The bbcode could look something like: 
`[itch]123456[/itch]`

By "hard coding" the first part of the source domain you could prevent users from linking to unwanted destinations.

[https://www.phpbb.com/community/viewtopic.php?f=46&t=693225](https://www.phpbb.com/community/viewtopic.php?f=46&t=693225)

(Since upload on the forum threads is pretty limited this would allow for a clean linking to published games)

**Comment by blurymind** [comment]
It is possible to simply embed the forum in an electron window, but not
sure how it would look... There are npm modules to render bbcode to html,
but i dont think that would be required. The forum already does it. It
would be nice to be able to embed the documentation in the ide and have it
even work offline. Not sure how safe it is to allow iframes in the forum.
If that is to ever happen it needs to be limited to safe domains. Steam or
itch seems ok

**Comment by 4ian** [comment]
I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/DBL5Ffmk/71-add-option-to-embed-itchio-steam-etc-on-forum

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)
