### ISSUE TITLE
[GD5] Object Image / Thumbnail not showing

### ISSUE THREAD

**Issue by rikazukun** [4ian/GD#559]
## Describe the bug
There are times (not frequent) when you add an image / animation to an object it doesn't show the image / thumbnail. It only shows a blank image when you import it from the project folder; if you import it from a different location it does show the image.

By default (on windows) the project files are created on C:\Users\[name]\GDevelop Projects\[folder]; this is in assumption that you didn't change anything when creating the project, other than the folder name.

## To Reproduce
A)
1. Create a project on the default location for Windows (C:\Users\[name]\GDevelop Projects\[folder]) folder = (default: My Project)
2. Add the images to the folder
3. Import it from the folder

This happens when you import an image to a project / scene which is already saved. I tried adding the assets first to a folder before saving / creating the project files and it shows just fine.
## Alternate Fix
- Creating the project folder on a different directory (ex: Documents, etc.) //This sometimes work
- Transferring the files before saving the scene / creating the project itself

## Other details
Windows 10 x64
GDevelop 5.0.0-beta45 (This also happens on the previous versions)

**Comment by 4ian** [comment]
Mmmm strange behaviour 🤔Is there any way you can get a video of it?

**Comment by rikazukun** [comment]
I tried reproducing the "so called bug" of mine, weird doesn't appear anymore, >.>; Thanks I'll be closing this now

**Comment by 4ian** [comment]
Ok, if it appears again, take a screenshot and you can also open the developer console (View > Toggle Developers Tools) and copy/paste here the content so that I may find more information :)
