### ISSUE TITLE
[GD5] Example: Creating an object at the center of another object

### ISSUE THREAD

**Issue by rikazukun** [4ian/GD#560]
Hi!

I'd like to submit a new example to be added to GDevelop.

I confirm that any assets can be used freely by anybody, including for commercial usage.

[CenterObjectWithinAnother.zip](https://github.com/4ian/GD/files/2212256/CenterObjectWithinAnother.zip)

**Comment by 4ian** [comment]
Added for next version! Thanks a lot!! 😃
I think I could work on having the web-app support opening directly an example from a link. Would help to share the example in the wiki or on the web (something like: `https://editor.gdevelop-app.com?open-example=center-object-with-another`).
