### ISSUE TITLE
[GD5] Example: Bomb The Crate

### ISSUE THREAD

**Issue by rikazukun** [4ian/GD#561]
Hi!

I'd like to submit a new example to be added to GDevelop.

I confirm that any assets can be used freely by anybody, including for commercial usage.

~ I do not own the assets used in this example; it is available and completely
free at https://opengameart.org/content/bomb-party-the-complete-set
Credits to: Cem Kalyoncu/cemkalyoncu (for the modified version of the spritesheet) and
to Matt Hackett/richtaur (for the original version of the spritesheet)

[BombTheCrate.zip](https://github.com/4ian/GD/files/2214451/BombTheCrate.zip)

**Comment by 4ian** [comment]
Cool! Thanks! 👍

I've made a few changes:
- Use a tiled sprite object for the grass - it has better rendering performance and it's easier to use than copy/paste a lot of times the same object :)
- Remove the platformerobject and platform behaviors. Instead, for collision handling when your game is not a platformer, it's better to simply call the action "Separate two objects", giving your player and the group of objects that are solid ("Unmovables" in your example). The platformer behavior is using this internally, but also doing a lot of other things so better just use this action to handle collisions :)
- Remove a useless object and useless resources

Will add it to the next version. Thanks a lot!!

**Comment by rikazukun** [comment]
Thanks! 

- Originally it was a tiled sprite for the grass; I forgot to change it back, cause I was planning on making the bomb be centered on every grass when it collides with the bomb created.

- I see, I didn't know / haven't tested that function yet so I wasn't able to use it properly (that's why I used the platformer behavior instead)

**Comment by 4ian** [comment]
> Originally it was a tiled sprite for the grass; I forgot to change it back, cause I was planning on making the bomb be centered on every grass when it collides with the bomb created.

What you can do is, instead of testing for collisions which is expensive, round up the position of the bomb:

Do =Round(Bomb.X()/64)*64 to the X position of Bomb
Do =Round(Bomb.Y()/64)*64 to the Y position of Bomb

(if 64 is the size of the "virtual grid" that you're using).

> I see, I didn't know / haven't tested that function yet so I wasn't able to use it properly (that's why I used the platformer behavior instead)

Yes, it's not known enough and not discoverable easily, I'm thinking about how it could be made more discoverable. Maybe some pages in the wiki.

**Comment by rikazukun** [comment]
I see, by rounding it up it automatically acts like its on a grid. Thanks for the advice! It opened up other more possible games.

**Comment by 4ian** [comment]
Yes exactly :) Really not complicated, really fast and you're sure to have a *perfectly* aligned grid!

**Comment by rikazukun** [comment]
I updated mine now, thanks; probably if other more changes should be applied, I'll change the collision masks, (customize them) to be more accurate.

**Comment by 4ian** [comment]
It should be online on https://editor.gdevelop-app.com?project=bomb-the-crate :) 
See my updated version here: https://github.com/4ian/GD/tree/master/newIDE/app/resources/examples/bomb-the-crate

**Comment by rikazukun** [comment]
Cool, I just checked it; it's nice, I also applied some stuff on mine, alongside with your changes. I also made the hitboxes more accurate so it doesn't trigger the collision for other crates even if its far away, and also the z-order of the walls to make it more bomberman-ish.
[BombTheCrateUpdated.zip](https://github.com/4ian/GD/files/2214718/BombTheCrateUpdated.zip)

**Comment by 4ian** [comment]
There seems to be a few issues with this, I can partially walk on the walls. I think the hit boxes when be need placed properly: 
<img width="912" alt="screenshot 2018-07-25 22 12 20" src="https://user-images.githubusercontent.com/1280130/43227903-008735b6-9058-11e8-8362-29059f4d44a0.png">
<img width="912" alt="screenshot 2018-07-25 22 12 55" src="https://user-images.githubusercontent.com/1280130/43227904-00a1a9dc-9058-11e8-9564-87144c95eaef.png">

**Comment by blurymind** [comment]
If the walls are supposed to partially obscure the player when he is behind
them, you might need some z order logic

**Comment by rikazukun** [comment]
I don't have any problems with my version, this is a re-upload; (I even re-created the hitboxes), try to check it out.

- The head on the previous versions was intentionally made to overlap walls and such to show a bit more realism or a what if, than having it bump instead (changed)

- The overlap on that image must be on that specific frame only, I checked it now and doesn't show like that.

[Uploading BombTheCrate7-26-2018.zip…]()

**Comment by 4ian** [comment]
I've updated the example, thanks :)
I've removed a useless platformer character behavior that was still there, two useless resources and changed the size of the window so that it display all the blocks :)

Thanks again for working on this 👍

**Comment by 4ian** [comment]
Closing as the example is added to the new release :)
