### ISSUE TITLE
I can not installed GD5 on window 32bit. Is there a way to install it?

### ISSUE THREAD

**Issue by nhutcr0** [4ian/GD#567]

**Comment by nhutcr0** [comment]
It warns me "You need window 64bit"

**Comment by nhutcr0** [comment]
Does GD5 setup not support windows 32bit?

**Comment by Lizard-13** [comment]
official GD5 builds are 64-bits only, don't know if what Wend1go says will work, but you can compile it yourself too.
Also, if you aren't going to use the bug template please delete all the extra text ;)

**Comment by nhutcr0** [comment]
Thank Lizard-13
