### ISSUE TITLE
[GD5] Error Debugger | Max Payload size exceeded

### ISSUE THREAD

**Issue by Bouh** [4ian/GD#570]
## Describe the bug
Error of debugger, 'Max Payload size exceeded'
This error requires to kill process.

## To Reproduce
[Here in video](https://youtu.be/2kyDLLCGlYg?t=1857) 

* Please include a link to a game if possible!
Ask to Jiminus for it (available on Discord or YouTube )

Screen Error provide from video :
![](https://cdn.discordapp.com/attachments/258624058604781568/473800782827749376/bug.png)
![](https://cdn.discordapp.com/attachments/468835859240845313/473894300208332801/unknown.png)

## Other details
Windows 10, GD5 Desktop (GDevelop 5.0.0-beta45 based on GDevelop.js 4.0.97-0-release)

**Comment by 4ian** [comment]
Fixed in e4b2fe677bfe855b3991fc33a0ec9dbb1ef3e55b
The problem was that the structure used by pathfinding to store the position of objects is a complex one (a hierarchical spatial hashing grid) which was wrongly serialized and sent to the debugger.
