### ISSUE TITLE
Double-clicking object to edit it, closing window, and then clicking stage places unnecessary copy of object

### ISSUE THREAD

**Issue by kryptot7** [4ian/GD#574]
## Describe the bug
Double-clicking an object in the object list to edit it, closing the resulting window, and then clicking the stage places an unnecessary copy of the object onto the stage.

## To Reproduce
1. Double-click an object in the object list to edit it
2. Press Cancel to close the animations/behaviors/properties window
3. Click the stage
4. A copy of the object will be spawned where you clicked, but this is unexpected

## Other details
Windows 10 1803 64-bit / GDevelop 5.0.0-beta47

**Comment by 4ian** [comment]
Closing this as it should be fixed for next version! :) Thanks @kryptot7 for reporting this with the template and @Wend1go for fixing this super quickly 💪 💪
