### ISSUE TITLE
Can't start exported game

### ISSUE THREAD

**Issue by Jeje2201** [4ian/GD#592]
## Describe the bug
When im done with exporting my game with the .exe format from Gdevelop. I can't start it, getting an error message : " Windows can't seem to access the driver, folder, or specifiq file. You may not have the proper right to access the element"
It's being download in my "download" folder, any other files I have can be edit, delete, and start.
I tried with an other game (both projects were develop from the first release of Gd5) and still getting the same error.
I downloaded the logs file, but im getting : "Build succeeded, no log provided.".

If needed, here is the download link that I got : https://s3-eu-west-1.amazonaws.com/gd-build/c1d353c3-ede2-4757-9642-bb7883f1ea52/game-windows.exe

![screenshot_7](https://user-images.githubusercontent.com/19387127/44617073-d6436a00-a85c-11e8-9f03-6daea83e7a9b.png)

## To Reproduce
1. Export a game from the .exe format
2. Start it

## Other details
Windows 10, Gdevelop V48
I can provide other screenshot : 
![screenshot_2](https://user-images.githubusercontent.com/19387127/44617099-641f5500-a85d-11e8-8e74-4e2ce84e99a1.png)
![screenshot_4](https://user-images.githubusercontent.com/19387127/44617103-6e415380-a85d-11e8-9476-cec6e52cd2b3.png)
![screenshot_3](https://user-images.githubusercontent.com/19387127/44617105-739e9e00-a85d-11e8-9645-5a2ed2c0dcea.png)

**Comment by Jeje2201** [comment]
-- Update --
I downloaded the zip file, unziped it in a folder, started the .exe file and it worked, so it seem to be the .exe export that got a problem

**Comment by 4ian** [comment]
Is it possible that your antivirus is blocking the executable to be started?

**Comment by rikazukun** [comment]
Did you manually compiled it via electron builder on the first try? or was it using the online export? Else must be the case what 4ian said.

**Comment by KinkGD** [comment]
I've downloaded : https://s3-eu-west-1.amazonaws.com/gd-build/c1d353c3-ede2-4757-9642-bb7883f1ea52/game-windows.exe

Double clicked => the Game auto install without problem and runs without problem.

Maybe like 4ian said it's blocked by your antivirus, or Windows Smartscreen ?

What's happen if right click => Execute as administrator ?

**Comment by Jeje2201** [comment]
Sorry for the lack of answer, I was busy this weekend
As you stated @4ian , Avast was indeed the problem. Maybe should be cool to warn people when they export the game that antivirus can block the game to be start ? Or changed how is code the export so antivirus don't think our games are virus ?

**Comment by rikazukun** [comment]
Can just manually compile it via electron-builder like what I've mentioned  ^.

**Comment by 4ian** [comment]
Note that the online export is basically only running electron-builder so should not in theory changes anything. I think it's Avast being picky because the executable is extracting the game files :/
