### ISSUE TITLE
GD5 v50 : image name of a texture particle object is "corrupted" after save/close open a project

### ISSUE THREAD

**Issue by KinkGD** [4ian/GD#607]
## Describe the bug
The bug appears in IDE while editing a particule emitter object, with a texture image as particule. After saving, closing, and opening the project again, the name in the field looks like this : 
![image](https://user-images.githubusercontent.com/8144048/44876879-90463600-aca2-11e8-9078-9f3631a4048e.png)

## To Reproduce
1. Create a new project
2. add a particle emitter object
3. Select a texture image (or draw a new with piskel), click "OK"
4. Save the project
5. close the project
6. open the project
7. Edit the particle meitter object

I think i noticed it before in V48, but since it doesn't break game (because the particle keep working normally in preview/exported game), i was just thinking i was tired.

**Comment by 4ian** [comment]
I see what's wrong

**Comment by 4ian** [comment]
Fixed in 563bc6c64cd5acc5f28b7209b8b822f2ff1a757d! Nasty error as it went undetected. 
Fix will be in beta 51, hope to be able to upload it very soon :) 

Thanks for reporting the issue!
