### ISSUE TITLE
Fonts not working on gdev50-beta

### ISSUE THREAD

**Issue by tunafishesgames** [4ian/GD#609]
so about a month ago I made my first game, I used a font for my game and it worked fine and even in preview mode on gdev-beta40. but when gdev-beta50 came out I got very excited so i was planning to make a game on it. but when I put in my font its wasn't working, so i tried it again, the same thing. If anybody knows pls help. so gdev pls improve the font feature.

**Comment by 4ian** [comment]
Sounds like a duplicate issue as https://github.com/4ian/GD/issues/536! Closing this issue in to avoid duplicate, let's continue discussion on the other :)
