### ISSUE TITLE
Number of remaining builds for today

### ISSUE THREAD

**Issue by KinkGD** [4ian/GD#612]
i've made several android package (apk) today, but the number of remainings builds for today doesn't decrease.

So i always have "10 remaining builds for today"..

It sounds good to me to have unlimited number of builds remaining, but i guess something is going wrong hehe.

**Comment by 4ian** [comment]
Useful for you 😛
Can you double check if it's not an issue of refreshing the interface? Basically just quit and relaunch GDevelop and see if the count changed?

Packaging that failed are not counted toward the limit, but I guess they are working?

**Comment by KinkGD** [comment]
Yes, my package were sucessfull ! And yes, it seems to be normal today, (6 of 10 remaining builds for today). But strange things, i restarted Gdevelop many times yesterday, trying to refresh, but it was always 10/10 remaning...

I think this ticket can be closed, i'll comment if (and when) it occurs again.

**Comment by 4ian** [comment]
Ok let me know and I can check your account limits in this case! :)
