### ISSUE TITLE
Default "Activate behavior" status is not picked when the action is validated

### ISSUE THREAD

**Issue by KinkGD** [4ian/GD#617]
GD 5.b51, windows 10

## Description : 
On validation on action "activate behvior", default no status is picked, but is missing in event sheet after validating.

## To Reproduce
1. Create a new object, edit behavior of the object and select for example "draggable"
2. In actions : choose the action "Activate behavior", select the object created in 1) 
3. As you can see here, "No" is selected by default, without any click from a user : 
![image](https://user-images.githubusercontent.com/8144048/45056042-03302200-b092-11e8-8eb6-0c957c3c75e9.png)
4. Click "Done"
5. Check the event sheet : the "no" status is missing
![image](https://user-images.githubusercontent.com/8144048/45056078-278bfe80-b092-11e8-942a-a254386b1327.png)

**Comment by Lizard-13** [comment]
I think I've seen others conditions/actions that says "Yes by default" but the default value is set to "No", surely it's related

**Comment by 4ian** [comment]
I've fixed the "No" being highlighted even when no choice was made. So it will be clearer that nothing was chosen.
The ideal situation would have a default value chosen but for now I think it's better :)

**Comment by 4ian** [comment]
Closing as the fix should be in the next version.
