### ISSUE TITLE
Ability to set a vertical gradient as background

### ISSUE THREAD

**Issue by blurymind** [4ian/GD#618]
## Description
More often than not I set a vertical gradient as a base background. It just makes for a more interesting background base than flat color. 

I know that in html it is pretty easy to do via some simple css, but seeing as to there were recently some flickering problems with backgrounds - not sure if it would be that easy to do in GD. If this is a tall order - please just close this request.

## Solution suggested
The actual background property could have a second optional color - if chosen - use a gradient instead of flat color

## Alternatives considered
A simple workaround to this is to create a gradient image in photoshop - a 1px width by whatever the height of game screen is. Then assign the image to a tiling sprite and tile it horizontally

**Comment by 4ian** [comment]
Mmm, I think it's quite complex to make, we would need to generate a texture (potentially slowing down game startup), create the gradient, then create a PIXI/Cocos2d-JS object automatically displayed in the background. 
This is cumbersome to do and I don't feel like a huge demand for this. Pretty sure on the contrary that if I add this, after we'll be asked for radial gradients, gradient with multiple stops, gradient with transparency, gradients that change colors, gradients that are rotated so we'll have to create actions/conditions for gradients, etc...

I think it's not the job of GDevelop to take care of this and fair to let this to the game author. The alternative you mentioned (a 1px width image) is perfectly valid, efficient, flexible (you can do everything I said, and even more with a sprite object, like blend modes) - so I'm in favor of using it if someone need a gradient :)

**Comment by blurymind** [comment]
@4ian yes good point :)
