### ISSUE TITLE
Search features and comments enhancements : colors, 2 columns, search in action/condition/comments..

### ISSUE THREAD

**Issue by KinkGD** [4ian/GD#624]
Hello,

Suprisingly, i didn't see any discussions or trello card's about this : possibility to search in comments.

In GD4, i was used to have a lot of #hashtags in my comments to easily find events related to something, so i'm considering this might be great that the search fields parse also the comments of the events sheet. I also used a lot of colors and 2 columns comments.

Other ideas about comments : 
- Colors ! (like in GD4)
- 2 Columns (like in GD4) : so usefull.. i usually use my hashtags in second column.

Other ideas about "search" feature : 
- Search only in actions (like GD4)
- Search only in conditions (Like GD4)
- Search only in "comments", or only in "group names" (new suggestions)

These features from GD4 are really missing right now on long event sheet.

**Comment by 4ian** [comment]
Created this card for colors and two columns: https://trello.com/c/IDPblXbs/151-add-support-for-changing-comments-color-and-optionally-have-two-columns-in-the-comment-text

This is not high priority but could indeed but re-implemented for GD5 (using only JS, as everything is already ready in the C++ codebase for `gd.CommentEvent`).

For searching in comments, that would be useful indeed, also created a card: https://trello.com/c/Vm2M51NM/152-make-search-in-events-also-search-in-the-content-of-the-comments

For restricting search, the card is already there: https://trello.com/c/WwPJBT8K/121-add-support-for-searching-replacing-in-events-in-the-current-selection - I've added in the title about restricting search to actions/conditions. Searching in the selected events is a bit complex, but restricting search to actions and conditions could I think be implemented easily in JS.

(Closing this as cards created and I keep the open issues for bugs, discussion can continue here though)
