### ISSUE TITLE
Mac OS X 10.10+ version

### ISSUE THREAD

**Issue by tluyben** [4ian/GD#64]
I did some work on it, but cannot get the build to finish on Yosemite. After fixing all the other errors, the errors still popping up are related to wxwidgets and there my knowledge of linking internals ends ; I would not know how to fix those. Here they are;

https://gist.github.com/tluyben/b7777f0f766bddf93d2a

wxwidgets is the latest (3.0.2 which is included does not actually compile on Yosemite) from git; it compiles fine, for x86_64, but linking (with GD, nothing to do with wxwidgets it seems) just gives these errors.

I think after this hurdle it'll run though; any idea what causes this?

**Comment by victorlevasseur** [comment]
When you have built wxWidgets, have you followed the step in WXWIDGETS_SOURCE_FOLDER/docs/osx/readme.txt ?

**Comment by 4ian** [comment]
@tluyben I would be interested in trying to compile GD on Mac OS X using teamviewer. :smiley: But I think it could take a lot of time and I don't want to bother you! Will you be able to use another computer while I'm trying to compile using teamviewer?

**Comment by tluyben** [comment]
Sorry for the belated response, but that's fine; I just spun up a new VM, you can use it. Can you mail me so we can exchange credentials? You can tinker as long as you want, but as you wrote this project, I don't think it will take you a long time :) It's probably my quite novice wxWidgets/C++ knowledge holding me back here.

**Comment by 4ian** [comment]
Not sure where I can get your email address? Mine is Florian.rival [at] gmail.com :)

**Comment by 4ian** [comment]
I'm doing tests for compiling GD on Mac: the ``atom``related error is due to the flag ``-s`` being used, it should be removed when not compiling with gcc.

**Comment by 4ian** [comment]
Should be fixed now :) I still have to write doc on how to build on MacOS but with homebrew and by following the traditional cmake workflow, should be quite easy :)
