### ISSUE TITLE
Build may fail in improved-extlibs-cmakelists

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#66]
Some builds fail because the SFML library is not built before a lib/exe that needs it (when using multiple cores to build like make -j4).
Error message : no target to make libsfml-graphics/audio or ... .so
Maybe you need to link against sfml-graphics instead of libsfml-graphics.so in CMakeLists.txt as now SFML is a part of the project building process.

**Comment by 4ian** [comment]
Did you experienced this build fail? Anyway, you're right as SFML is part of the building process I should indeed use the target names instead of the raw .a/.so filename. I'll changed it tomorrow :)
Thanks!

**Comment by victorlevasseur** [comment]
Build is failing on OpenSUSE and on the OpenSuse Build Service. Travis-CI has also the same errors (I think, the log is incomplete) for improved-extlibs-cmakelists.

**Comment by 4ian** [comment]
Mmm yeah indeed, I was convinced that the Travis CI build was going ok! 
But I'll fix that tomorrow :)

**Comment by 4ian** [comment]
I've made several corrections, the Travis CI build is now ok (and even faster thanks to using make -j4. I've also made sure that the log is not too long).
Let me know if you still can't compile GD (I've merged the branch on master), normally as long as SFML dependencies and wxWidgets are installed, everything should now be ok! :smile:

**Comment by victorlevasseur** [comment]
Working perfectly now :+1:

**Comment by 4ian** [comment]
Yeeeah!
