### ISSUE TITLE
Player stuck when removing the platform he is on

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#79]
The player is not totally stuck but fall very slowly and can jump at any moment).
Happens only in HTML5 games.

**Comment by 4ian** [comment]
Strange that the behavior varies in native and HTML5 games as the code should be the same. I'll take a look!

**Comment by victorlevasseur** [comment]
Should be tested again as you optimized the platformer automatism.

**Comment by 4ian** [comment]
Mmm, optimisations were made mainly on the implementation to avoid using `for in` loops that JS engines can't JIT compile and optimize. So normally the behaviors of objects didn't change and the issue is still here!

**Comment by 4ian** [comment]
Closing as this should not be happening now. Feel free to open a new issue if there is still a reproducible issue :)
