### ISSUE TITLE
Releasing GDevelop 3.6.79

### ISSUE THREAD

**Issue by 4ian** [4ian/GD#95]
I think it's time to release GD 3.6.79: I'd like to get feedbacks (@victorlevasseur ?) to know if you think there are still major issues to fix or if everything looks ok?

My Ubuntu/Windows computer sort of crashed (Ubuntu crashed last time with an alarming error concerning sda, I didn't get any time to check this out since I'm working on the Mac I have now) so I didn't made extensive tests on real systems these latest times, just checked compilation and if basic things work on VMs.

**Comment by victorlevasseur** [comment]
Some month ago, you said that you will publish a beta version (because of c++11). Do you still want to do it ?

**Comment by 4ian** [comment]
Well I guess there is no need to mark it as "beta", but it's a good idea to release it only on GitHub + the forum at first, and then publicly on the website (+ the updater of the software) if everything is ok. :smiley: 

So the usual process, often after releasing a new version with major changes, I put it on the forum only and I make another release some days after to fix bugs that I didn't catch at first.

**Comment by victorlevasseur** [comment]
You've forgotten to update the translation on Crowdin because there are some new strings to translation (the animation speed scale for example).

**Comment by victorlevasseur** [comment]
Found a little bug in an example : #96

**Comment by 4ian** [comment]
Updated the translations, but I should probably update them again soon because translators are working on some languages (portuguese for example).

**Comment by victorlevasseur** [comment]
When using C++ events under Windows, I get an **undefined reference**.

**Comment by victorlevasseur** [comment]
And even not compiled. I can provide an example if needed.

**Comment by 4ian** [comment]
An example would be handy :)

**Comment by victorlevasseur** [comment]
Here it is : http://www.victorlevasseur.com/down/ExampleGrayPause.zip

**Comment by victorlevasseur** [comment]
Have you been able to find the problem ? I must admit that all the compilation management code of GDevelop is still a mystery to me.

**Comment by 4ian** [comment]
I understand, not the simplest part of GD indeed :)
Sorry I was doing other things including setting up translated versions of the website. But fixing this errori is my next task! ;)

**Comment by 4ian** [comment]
@victorlevasseur Could you try with latest commit? https://github.com/4ian/GD/commit/54ec6d07376918321e692a2f610d50181f5af0f9

Should be working normally (the example still have errors but it's related to the C++ code :wink:)

**Comment by 4ian** [comment]
@victorlevasseur I've checked, your example works properly when adding "GDCpp/ImageManager.h" in the include files :smile: 

I'm going to release the new version as I think everything is ok now :)

**Comment by victorlevasseur** [comment]
Should I send the new version to the OBS ?

**Comment by 4ian** [comment]
Yup, you can send it :)

**Comment by victorlevasseur** [comment]
Sent, it's currently building the packages.

**Comment by 4ian** [comment]
Cool! Compiling the Ubuntu package right now. I've updated the release description, I'll announce the update on the forum and if everything is ok activate the update from the software in a few days. :)

**Comment by victorlevasseur** [comment]
The new packages are now avaible for Fedora 21, Arch Linux and openSUSE 13.2/Tumbleweed.

**Comment by 4ian** [comment]
Sweet :+1:
I didn't had the time to finish Ubuntu ppa upload for trusty but I'll do it today and announce the release. :smile:

**Comment by 4ian** [comment]
Online and announced :)
